### ISSUE TITLE
预览 :LeaderF file 结果报错了

### ISSUE THREAD

**Issue by cage1618** [Yggdroot/LeaderF#1020]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
```
  NVIM v0.8.1
  Build type: Release
  LuaJIT 2.1.0-beta3
  Compiled by brew@Catalina
  
  Features: +acl +iconv +tui
  See ":help feature-compile"
  
     system vimrc file: "$VIM/sysinit.vim"
    fall-back for $VIM: "/usr/local/Cellar/neovim/0.8.1/share/nvim"
  
  Run :checkhealth for more info
```   

- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): -
- Output of `:echo &pythonthreedll`(only vim, not neovim): -
- Output of `:py print(sys.version)`: 
```
3.9.15 (main, Oct 11 2022, 22:25:13)
[Clang 12.0.0 (clang-1200.0.32.29)]
```
- Output of `:py3 print(sys.version)`: 
```
3.9.15 (main, Oct 11 2022, 22:25:13)
[Clang 12.0.0 (clang-1200.0.32.29)]
```
- Output of `:echo g:Lf_Debug_Cmd`: 
```
E121: Undefined variable: g:Lf_Debug_Cmd
```
- Output of `:echo g:Lf_FilesFromCache`: 
```
E121: Undefined variable: g:Lf_FilesFromCache
```

- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
Plug 'Yggdroot/LeaderF', {'do': 'LeaderfInstallCExtension'}
let g:Lf_HideHelp = 1
let g:Lf_WindowHeight = 15
let g:Lf_StlColorscheme = "gruvbox_material"
let g:Lf_PreviewResult = {'rg': 0, 'BufTag': 0, 'File': 0}
let g:Lf_StlSeparator = {'left': '', 'right': ''}
let g:Lf_ShowDevIcons = 1
let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1
let g:Lf_PopupWidth = 0.85
let g:Lf_PopupHeight = 0.382
let g:Lf_PopupPreviewPosition = 'bottom'
let g:Lf_PopupPosition = [-1000, 0]
let g:Lf_GtagsAutoGenerate = 1
let g:Lf_Gtagsconf='/usr/local/share/gtags/gtags.conf'
let g:Lf_Gtagslabel = 'native-pygments'
let g:Lf_ShowHidden = 1
```

### Describe your question, feature request, or bug.
预览 :LeaderF file 结果报错
![image](https://github.com/Yggdroot/LeaderF/assets/2541448/f8c6528d-cff5-4407-ba7b-2b80d0889736)

### Steps to reproduce
 :LeaderF file <Enter>
control + p 预览 （我这是手动预览）

### Actual behaviour
```
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy[1]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/cage/.vim/plugins/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 818, in start
    the_args.start(arguments, *args, **kwargs)
  File "/Users/cage/.vim/plugins/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 750, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/Users/cage/.vim/plugins/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 827, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/Users/cage/.vim/plugins/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2533, in startExplorer
    self.input()
  File "/Users/cage/.vim/plugins/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 62, in deco
    func(self, *args, **kwargs)
  File "/Users/cage/.vim/plugins/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2880, in input
    self._previewResult(True)
  File "/Users/cage/.vim/plugins/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 405, in _previewResult
    self._previewInPopup(line, self._getInstance().buffer, line_nr)
  File "/Users/cage/.vim/plugins/LeaderF/autoload/leaderf/python/leaderf/devicons.py", line 414, in deco
    return func(*args, **kwargs)
  File "/Users/cage/.vim/plugins/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 842, in _previewInPopup
    self._createPopupPreview(line, source, 0)
  File "/Users/cage/.vim/plugins/LeaderF/autoload/leaderf/python/leaderf/utils.py", line 1419, in deco
    return func(self, *args, **kwargs)
  File "/Users/cage/.vim/plugins/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 859, in _createPopupPreview
    self._createPopupModePreview(title, source, line_nr, jump_cmd)
  File "/Users/cage/.vim/plugins/LeaderF/autoload/leaderf/python/leaderf/utils.py", line 1419, in deco
    return func(self, *args, **kwargs)
  File "/Users/cage/.vim/plugins/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 665, in _createPopupModePreview
    self._createPreviewWindow(config, source, line_nr, jump_cmd)
  File "/Users/cage/.vim/plugins/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 484, in _createPreviewWindow
    self._preview_winid = int(lfEval("nvim_open_win(g:Lf_preview_scratch_buffer, 0, %s)" % str(config)))
  File "/usr/local/lib/python3.9/site-packages/pynvim/plugin/script_host.py", line 205, in eval
    obj = self.request("vim_eval", expr)
  File "/usr/local/lib/python3.9/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim:E5555: API call: Invalid key: 'title_pos'
```

### Expected behaviour
可以正常预览

**Comment by cage1618** [comment]
esc或回车关闭报错信息后，<c-j> 或 <c-k> 也无法移动光标了

**Comment by Yggdroot** [comment]
哦，是你用的nvim版本太低了，我原以为用nvim的都追新呢。
我改一下。

**Comment by cage1618** [comment]
😂多年前的老mbp，没有更新系统，装不了最新的nvim

**Comment by Yggdroot** [comment]
修复了。

**Comment by xrayw** [comment]
@cage1618 我也有一台2015款. 退回了catalina, brew有些不支持了..
但macports可以. 可以尝试一下.
