### ISSUE TITLE
5ad91dc is causing error

### ISSUE THREAD

**Issue by yangrq1018** [Yggdroot/LeaderF#1050]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
NVIM v0.10.0-dev-2063+ga767c046f
Build type: RelWithDebInfo
LuaJIT 2.1.1703358377
Run "nvim -V1 -v" for more info

- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]
- Output of `:py3 print(sys.version)`: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ x] Linux 
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
  {
    "Yggdroot/LeaderF",
    cmd = "Leaderf",
    build = function()
      if not vim.g.is_win then
        vim.cmd(":LeaderfInstallCExtension")
      end
    end,
  },
```

### Describe your question, feature request, or bug.
Leader f rg is printing python exception on selection.
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/martin/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line
 821, in start
    the_args.start(arguments, *args, **kwargs)
  File "/home/martin/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line
 753, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/home/martin/LeaderF/autoload/leaderf/python/leaderf/rgExpl.py", line
1137, in startExplorer
    super(RgExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/home/martin/LeaderF/autoload/leaderf/python/leaderf/manager.py", line
 2799, in startExplorer
    self.input()
  File "/home/martin/LeaderF/autoload/leaderf/python/leaderf/manager.py", line
 62, in deco
    func(self, *args, **kwargs)
  File "/home/martin/LeaderF/autoload/leaderf/python/leaderf/manager.py", line
 3080, in input
    if self.accept() is None:
       ^^^^^^^^^^^^^
  File "/home/martin/LeaderF/autoload/leaderf/python/leaderf/manager.py", line
 2373, in accept
    self._accept(file, mode, self._getInstance().buffer, line_num) # for bufTa
g
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/LeaderF/autoload/leaderf/python/leaderf/utils.py", line 1
419, in deco
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/LeaderF/autoload/leaderf/python/leaderf/manager.py", line
 2264, in _accept
    self._acceptSelection(file, *args, **kwargs)
  File "/home/martin/LeaderF/autoload/leaderf/python/leaderf/rgExpl.py", line
20, in deco
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Steps to reproduce
Use leader f rg search, type something to search for,
choose any entry from the result, hit enter, then the error logging shows up.

The jump is fine, though. Dismiss the error then we can jump to that file.

### Actual behaviour
See above.

### Expected behaviour
Select the result should not print any error.

**Comment by yangrq1018** [comment]
```
diff --git a/autoload/leaderf/python/leaderf/rgExpl.py b/autoload/leaderf/python/leaderf/rgExpl.py
index bc23f61..7f7ba80 100644
--- a/autoload/leaderf/python/leaderf/rgExpl.py
+++ b/autoload/leaderf/python/leaderf/rgExpl.py
@@ -594,6 +594,7 @@ class RgExplManager(Manager):
             else:
                 lfCmd("hide buffer +%s %s" % (line_num, buf_number))
             lfCmd("norm! ^zv")
+            lfCmd("call search('%s', 'zW', line('.'))" % escQuote(self._getExplorer().getPatternRegex()[0]))
             lfCmd("norm! zz")
 
             if "preview" not in kwargs:
```
This is definitely causing the issue. getPatternRegex() returns nothing.

**Comment by Yggdroot** [comment]
Fixed, thanks.

**Comment by yangrq1018** [comment]
Fixed.
