### ISSUE TITLE
vim 7.4 compatibility

### ISSUE THREAD

**Issue by ykqiu** [Yggdroot/LeaderF#1095]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`:  7.4
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 0
- Output of `:echo &pythondll`(only vim, not neovim): undefined
- Output of `:echo &pythonthreedll`(only vim, not neovim): undefined
- Output of `:py print(sys.version)`: 2.7.5 (default, Jun 28 2022, 15:30:04)
- Output of `:py3 print(sys.version)`: no
- Output of `:echo g:Lf_Debug_Cmd`:  undefined
- Output of `:echo g:Lf_FilesFromCache`: undefined
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
default configuration
### Describe your question, feature request, or bug.
has('patch330') is 1, so I think it match the requirement in README
vim7.3 or higher. Only support vim7.4.330 or higher after v1.01.
but:

when start LeaderF for first time:
Error detected while processing function leaderf#Any#start..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/qiuyuankun/.vim/bundle/LeaderF-master/autoload/leaderf/python/leaderf/anyExpl.py", line 838, in start
    the_args.start(arguments, *args, **kwargs)
  File "/home/qiuyuankun/.vim/bundle/LeaderF-master/autoload/leaderf/python/leaderf/anyExpl.py", line 756, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/home/qiuyuankun/.vim/bundle/LeaderF-master/autoload/leaderf/python/leaderf/fileExpl.py", line 827, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/home/qiuyuankun/.vim/bundle/LeaderF-master/autoload/leaderf/python/leaderf/manager.py", line 2774, in startExplorer
    self._getInstance().enterBuffer(win_pos, not isinstance(content, list))
  File "/home/qiuyuankun/.vim/bundle/LeaderF-master/autoload/leaderf/python/leaderf/instance.py", line 1214, in enterBuffer
    self._createBufWindow(win_pos)
  File "/home/qiuyuankun/.vim/bundle/LeaderF-master/autoload/leaderf/python/leaderf/instance.py", line 931, in _createBufWindow
    lfEval("get(g:, 'Lf_PopupColorscheme', 'default')")))
vim.error: Vim(highlight):E421: Color name or number not recognized: ctermfg=-1 ctermbg=24
Error detected while processing function leaderf#Any#start:
line    4:
E171: Missing :endif
Press ENTER or type command to continue

### Steps to reproduce
print \f
### Actual behaviour
throw error messege
### Expected behaviour
no error

**Comment by Yggdroot** [comment]
I don't know where `ctermfg=-1` come from. Do you have any customized configuration?

**Comment by ykqiu** [comment]
> I don't know where `ctermfg=-1` come from. Do you have any customized configuration?

I have no configuration about ctermfg in my .vimrc, I grep "ctermfg" from my .vim dir and I found only vim-airline, leaderf and rainbow, these plugin dir show results. But there is no ctermfg=-1 from the grep results. I found a similar issue about this https://github.com/Yggdroot/LeaderF/issues/682

**Comment by Yggdroot** [comment]
Fixed.
