### ISSUE TITLE
Leaderf git diff 无法使用模糊搜索

### ISSUE THREAD

**Issue by keeferwu** [Yggdroot/LeaderF#1100]
在 vim 9.0 模糊搜索报错：

```
File "/home/qifeng/.vimplus/plugged/LeaderF/autoload/leaderf/python/leaderf/gitExpl.py", line 3340, in _acceptSelection^@    lfCmd(cmd)^@vim.error: Vim(py3):AttributeError: module 'fuzzy
Engine' has no attribute 'Category_GitDiff'
```
![PixPin_2024-09-11_11-06-13](https://github.com/user-attachments/assets/49c07b9a-cf52-44f6-afdd-2750d10f421c)

在 nvim 0.10.0 模糊搜索报错：

```
File "/home/qifeng/.vimplus/plugged/LeaderF/autoload/leaderf/python/leaderf/gitExpl.py", line 3340, in _acceptSelection^@    lfCmd(cmd)^@  File "/usr/local/lib/python3.8/dist-packages/py
nvim/api/nvim.py", line 311, in command^@    return self.request('nvim_command', string, **kwargs)^@  File "/usr/local/lib/python3.8/dist-packages/pynvim/api/nvim.py", line 199, in reque
st^@    res = self._session.request(name, *args, **kwargs)^@  File "/usr/local/lib/python3.8/dist-packages/pynvim/msgpack_rpc/session.py", line 139, in request^@    raise self.error_wrap
per(err)^@pynvim.api.common.NvimError: function leaderf#Any#start[4]..leaderf#LfPy[1]..provider#python3#Call[1]..leaderf#LfPy[1]..leaderf#Any#start[4]..leaderf#LfPy[1]..provider#python3#
Call, line 1: Vim(return):E5108: Error executing lua Vim:Error invoking 'python_execute' on channel 12 (python3-script-host):^@Traceback (most recent call last):^@  File "<string>", line
 1, in <module>^@  File "/home/qifeng/.vimplus/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 838, in start^@    the_args.start(arguments, *args, **kwargs)^@  File "/h
ome/qifeng/.vimplus/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 756, in _default_action^@    manager.startExplorer(win_pos[2:], *args, **kwargs)^@  File "/home/qife
ng/.vimplus/plugged/LeaderF/autoload/leaderf/python/leaderf/gitExpl.py", line 3322, in startExplorer^@    self.getExplManager(subcommand).startExplorer(win_pos, *args, **kwargs)^@  File 
"/home/qifeng/.vimplus/plugged/LeaderF/autoload/leaderf/python/leaderf/gitExpl.py", line 3578, in startExplorer^@    super(GitExplManager, self).startExplorer(win_pos, *args, **kwargs)^@
  File "/home/qifeng/.vimplus/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2885, in startExplorer^@    self.input()^@  File "/home/qifeng/.vimplus/plugged/LeaderF/au
toload/leaderf/python/leaderf/manager.py", line 62, in deco^@    func(self, *args, **kwargs)^@  File "/home/qifeng/.vimplus/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", l
ine 3123, in input^@    self._search(cur_content)^@  File "/home/qifeng/.vimplus/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1621, in _search^@    self._fuzzySearch
(content, is_continue, step)^@  File "/home/qifeng/.vimplus/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1956, in _fuzzySearch^@    pattern=pattern, category=fuzzyEn
gine.Category_GitDiff,^@AttributeError: module 'fuzzyEngine' has no attribute 'Category_GitDiff'^@stack traceback:^@^I[C]: at 0x5603fb4e8190^@^I[C]: at 0x5603fb4e8190  
```
![PixPin_2024-09-11_11-08-48](https://github.com/user-attachments/assets/a05e2ffc-71cf-4ea5-8f6f-9db1594b80f1)

**Comment by Yggdroot** [comment]
You should run :LeaderfInstallCExtension again. Because the C module has been changed.
