### ISSUE TITLE
Error after reload vimrc

### ISSUE THREAD

**Issue by bennyyip** [Yggdroot/LeaderF#132]
I copy this line from [doc](https://github.com/Yggdroot/LeaderF/blob/master/doc/leaderf.txt#L205) to my vimrc:
```
let g:Lf_StlSeparator = { 'left': "\ue0b1", 'right': "\ue0b2"}
```
The `font` field is missed, which should be
```
let g:Lf_StlSeparator = { 'left': "\ue0b1", 'right': "\ue0b2", 'font': ''}
```

LeaderF works well until `:source ~/.vim/vimrc`. When I invoke a LeaderF command, `:messages` gives following output:
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"~/.vim/vimrc" 945L, 29485C
Error detected while processing function leaderf#Mru#startExpl[2]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/benyip/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 731, in startExplorer
    self._getInstance().enterBuffer(win_pos)
  File "/home/benyip/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 225, in _getInstance
    self._afterExit)
  File "/home/benyip/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/instance.py", line 40, in __init__
    self._highlightStl()
  File "/home/benyip/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/instance.py", line 64, in _highlightStl
    lfCmd("call leaderf#colorscheme#highlight('{}')".format(self._category))
vim.error: Vim(if):E716: Key not present in Dictionary: font
Error detected while processing function leaderf#Mru#startExpl:
line    2:
E171: Missing :endif
1 more line

E474: Invalid argument
```

This seems like a regression, it didn't happen before. Should we update the [doc](https://github.com/Yggdroot/LeaderF/blob/master/doc/leaderf.txt#L205)?

**Comment by Yggdroot** [comment]
Thanks for reporting, this issue seems the same as issue #129, I 'll try to fix it.

**Comment by Yggdroot** [comment]
Fixed.
