### ISSUE TITLE
能否增加 LeaderfFunction! 叹号版本直接打开 normal 模式，并且定位到对应位置？

### ISSUE THREAD

**Issue by skywind3000** [Yggdroot/LeaderF#139]
tagbar 唯一一个方便的功能目前还不能代替，有这个就没有任何理由用 tagbar 了。

**Comment by Yggdroot** [comment]
可以，不过还是那句话，我没那么多时间在这个插件上，你如果可以的话，欢迎PR。

**Comment by skywind3000** [comment]
和厉不厉害无关啊，只和代码熟悉程度有关，我怕给你改砸了。你给个思路，改哪里，我来改都可以。

**Comment by skywind3000** [comment]
不然我改一大通，也许可以用了，但是可能有没考虑全的地方，或者有编码风格问题，又或者设计思路和你对 leaderf 的整体想法不一致了，你下不了决心merge，我要改可能要重写，就尴尬了，所以这个更改比上次复杂，你如果能给个思路，说改哪里，我做起来会更顺利些。

**Comment by Yggdroot** [comment]
我在想是让所有的命令都支持可以直接进入normal mode还是只是LeaderfFunction，如果只是LeaderfFunction，可以在https://github.com/Yggdroot/LeaderF/blob/559b80aad4960d20f97a82a42d30abb3f6ef17ac/autoload/leaderf/python/leaderf/functionExpl.py#L184
里面重写startExplorer()函数，
就像https://github.com/Yggdroot/LeaderF/blob/559b80aad4960d20f97a82a42d30abb3f6ef17ac/autoload/leaderf/python/leaderf/fileExpl.py#L566-L610
startExplorer()函数里只要不调用input()函数就是normal mode了,
https://github.com/Yggdroot/LeaderF/blob/559b80aad4960d20f97a82a42d30abb3f6ef17ac/autoload/leaderf/python/leaderf/manager.py#L756-L768
这里有3处input()调用，可以分别用if 条件包住，
```
if not 直接进入normal mode:
    input()
```
在https://github.com/Yggdroot/LeaderF/blob/559b80aad4960d20f97a82a42d30abb3f6ef17ac/autoload/leaderf/python/leaderf/manager.py#L722
里改还是重写我没太想好，你看看怎么更好。
def startExplorer(self, win_pos, *args, **kwargs): 需要一个参数表示`是否进入normal mode`，建议用kwargs，本来就是给扩展用的。

"光标移动到当前所在 tag位置的哪一行去", 进入normal mode就可以自己看着实现了。

**Comment by skywind3000** [comment]
好，我读读相关代码先

**Comment by Yggdroot** [comment]
想了一下，感觉有些麻烦，还是重写（override）def startExplorer()比较好，把影响仅限于LeaderfFunction。
因为tagbar也仅限于当前buffer，所以只要针对`LeaderfFunction`就行了，不需要针对`LeaderfFunctionAll`。主要因为`LeaderfFunctionAll`的getContent()函数返回的是迭代器，而不是list，它需要input()里的循环把结果显示在buffer中，如果针对`LeaderfFunctionAll`实现这个功能会很麻烦，也没这个必要。`LeaderfFunction`的getContent()函数返回的是list，只需要改下面这个if里的input()就行了（当然，是在override的def startExplorer()里改）。
https://github.com/Yggdroot/LeaderF/blob/559b80aad4960d20f97a82a42d30abb3f6ef17ac/autoload/leaderf/python/leaderf/manager.py#L748-L757

例如：
```
if 直接进入normal mode:
    光标移动到当前所在tag位置的那一行去()
else:
    input()
```
override `def startExplorer()`基本上就是code paste，有点难看，纠结~

**Comment by skywind3000** [comment]
今天读了一点点代码，或者改 manager 的 startExplorer，但是加个限制条件，只有 list 类型的可以直接进入 normal 模式，iterator 类型的针对文件，这种数量无穷无尽的列表，直接进入 normal 操作意义不大，比如我的 C:\Users\MyName 目录下面三万个文件，不经过模糊匹配默认 normal 模式我也几乎操作不了。

模糊匹配主要是针对已知的东西，比如熟悉项目的某文件名，而直接 normal 模式，更多的是起一个浏览的功能，function list 和 color scheme 这些一般数量一百以内东西列表，浏览还是比较常见的操作，所以可以提供直接进入 normal 模式，而文件列表那种动辄几万的迭代器，不仅筛选毫无浏览的可能，所以没必要提供。

你说那？

**Comment by Yggdroot** [comment]
我觉得可行。
有一点我还不太明白，`LeaderfFunction!`中感叹号怎么转化为参数？

**Comment by Yggdroot** [comment]
`:h :command-bang`，help了一下，好像有点明白了。

**Comment by Yggdroot** [comment]
第一个问题：可以在
https://github.com/Yggdroot/LeaderF/blob/96c22807b7920be46d63e05f5a7b159030908ca7/autoload/leaderf/python/leaderf/instance.py#L176-L182
180行下面获取原来的光标位置，
例如：`self._orig_cursor_pos = vim.current.window.cursor`
然后再写一个类似https://github.com/Yggdroot/LeaderF/blob/96c22807b7920be46d63e05f5a7b159030908ca7/autoload/leaderf/python/leaderf/instance.py#L285-L286
的函数。
第二个问题：是在https://github.com/Yggdroot/LeaderF/blob/96c22807b7920be46d63e05f5a7b159030908ca7/autoload/leaderf/python/leaderf/manager.py#L754-L755
这里写进buffer的。所以就像我之前说的：
```python
if 直接进入normal mode:
    光标移动到当前所在tag位置的那一行去()
else:
    input()
```
这样就行了。

**Comment by skywind3000** [comment]
为啥我在 instance.py 里面加了一个：

```python
	def getOriginalCursor(self):
		return self._orig_cursor
```

而在 manager.py 里面 startExplorer 里面调用这个方法有问题啊：

```python
        cursor = self._getInstance().getOriginalCursor()
```

报错：

```text
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "d:\acm\github\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 747, in startExplorer
cursor = self._getInstance().getOriginalCursor()
AttributeError: 'LfInstance' object has no attribute 'getOriginalCursor'
"manager.py" [unix] 888L, 34322C
"autoload\leaderf\python\leaderf\manager.py" 888 lines --84%--
"autoload\leaderf\python\leaderf\instance.py" [unix] 293L, 11133C
```

奇特了。

**Comment by skywind3000** [comment]
碰到个问题，我照你说的给 instance.py 加了个 getOriginalCursor 方法，返回的是在你说的 enterBuffer 位置增加的 self._orig_cursor 变量，平时测试正常，但是如果是第一次启动vim，没有打开任何文件的时候，乌干达那个界面下运行 LeaderfFunction 时，getOriginalCursor 就会报错说找不到 self._orig_cursor 变量，显然在 enterBuffer 的那句话没有被运行到，请问怎么解决？

![cursor](https://user-images.githubusercontent.com/3035071/39395970-6eb02b72-4b18-11e8-9afe-224943e2ee6b.png)

**Comment by skywind3000** [comment]
解决了，加了个  self._launched 的判断

**Comment by skywind3000** [comment]
最后一个问题，就搞定了，我在manager里面只改了一行，判断 kwargs 有 bang 就不调用 input，然后现卡在 functionexpl 里面：

```VimL
    def startExplorer(self, win_pos, *args, **kwargs):
        super(FunctionExplManager, self).startExplorer(win_pos, *args, **kwargs)
        if not self._launched:
            return 
        # a postfix bang sign, skip input() and locate cursor
        if kwargs.get('bang', False):
            self._relocateCursor()

    def _relocateCursor(self):
        orig_pos = self._getInstance().getOriginalPos()
        orig_line = self._getInstance().getOriginalCursor()[0]
        cbuffer = orig_pos[2]
        print dir(cbuffer)
```

这是给 functionExpl 加的两个新函数，在 relocate 哪里，如何得到 tag 信息：

1. tag 信息没有其他地方保存，只有从 vim.current.buffer 里面取出文本来自己分析么？
2. tag 信息是保证排序的么？

**Comment by Yggdroot** [comment]
没有排序，是https://github.com/Yggdroot/LeaderF/blob/96c22807b7920be46d63e05f5a7b159030908ca7/autoload/leaderf/python/leaderf/functionExpl.py#L124-L127
这条命令生成的。因为只是一个文件，所以tag还是有先后顺序的，就是按在文件中的前后顺序。
tag信息没有保存，只是在 vim.current.buffer中。

**Comment by skywind3000** [comment]
即便单个文件 ctags 的 -u 参数能保证按行号排序的么？不能保证的话我后面的逻辑就挂了，我在 FunctionExplorer._formatResult 多写点代码检测一下如果没有按行号排序就调用一次排序 OK 么？

**Comment by skywind3000** [comment]
做完啦，能不能帮看看：
https://github.com/Yggdroot/LeaderF/pull/143

现在支持：`LeaderfFunction!`, FunctionAll 太复杂，不是 list 好像是 iterator，我没敢动，不过重置光标那里留了给 FunctionAll 的代码。

**Comment by Yggdroot** [comment]
ctags -u应该可以保证按行号排序的，虽然我没有确切的证据。
刚测了一下，有几个小问题：
1. 有行尾空白
2. 每次运行LeaderfFunction!，左下角都有“searching”字符串，可以在 `self._getInstance().setBuffer(content)` 下面增加一句`lfCmd("echo")`
3. 跳到光标所在位置对应的tag好像有点bug。我直接试了LeaderF的源码，好像跳转没问题。试了一下c++和Java的code，跳不过去，光标停留在第一行。

**Comment by Yggdroot** [comment]
我还没有仔细看你的跳转算法的实现，我有个简单的思路：
假设原始光标所在的行为`n`，找到第一个大于`n`的那一行（每行都有行号），假设为`m`, 然后把光标跳到`m-1`行就行了。

**Comment by skywind3000** [comment]
好再整理下，我就是这么计算的，有问题的c++代码是哪个？我自己的c++代码可以正常跳转，你有问题的代码在网上么？我看看。

**Comment by Yggdroot** [comment]
我是随便找的，https://github.com/apache/hadoop/blob/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/io/serializer/JavaSerialization.java 和
https://github.com/apple/swift/blob/master/lib/AST/Pattern.cpp

**Comment by skywind3000** [comment]
其他几个问题以改，你给的这两个文件我这里都可以正常定位到 tag。奇特了

**Comment by skywind3000** [comment]
你重启一下vim试试？

**Comment by Yggdroot** [comment]
```python
+            try: 
+                ln = int(item[2][:-2], 0)
+            except:
```
try后面和
```python
+        if (not self._launched) or (len(args) > 0):
+            return 
```
return后面都有个空格。
我这边还是跳不过去，我debug一下吧。

**Comment by Yggdroot** [comment]
再一次谢谢你啊，帮我宣传一波后，星星几天涨了二三十个。

**Comment by skywind3000** [comment]
这回tagbar真的可以下课了，又没有函数原型，又不支持插入模式模糊匹配，关键还没有LeaderfFunction 好看，没事文章写出来摆着会满满发酵，有空我再写两篇

**Comment by sisrfeng** [comment]
For those who want to know what `LeaderF!` means:

I was confused with the bang `!` here, until I come here.

`nnoremap <C-B> :<C-U><C-R>=printf("Leaderf! rg --current-buffer -e %s ", expand("<cword>"))<CR><CR>`
