### ISSUE TITLE
LeaderfLine can't work after syntax off

### ISSUE THREAD

**Issue by fcying** [Yggdroot/LeaderF#164]
- vim or neovim?
    - [x] vim
    - [ ] neovim
- `vim --version` or `nvim --version`: vim 8.1 1-26

- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): libpython2.7.so.1.0
- Output of `:echo &pythonthreedll`(only vim, not neovim): libpython3.6m.so.1.0
- Output of `:py print(sys.version)`: 2.7.15 (default, May  1 2018, 20:16:04)[GCC 7.3.1 20180406]

- Output of `:py3 print(sys.version)`: 3.6.5 (default, May 11 2018, 04:00:52)[GCC 8.1.0]
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
    let g:Lf_PreviewCode = 0
    let g:Lf_DefaultMode = 'FullPath'
    let g:Lf_WildIgnore = {
           \ 'dir': ['.svn','.git','.hg'],
           \ 'file': ['*.sw?','~$*','*.bak','*.exe','*.o','*.so','*.py[co]']
           \}

    nnoremap ff :<C-u>LeaderfFile<CR>
    nnoremap fb :<C-u>LeaderfBuffer<CR>
    nnoremap fl :<C-u>LeaderfLine<CR>
    nnoremap fo :<C-u>LeaderfFunction<CR>
    nnoremap ft :<C-u>LeaderfTag<CR>
    nnoremap fm :<C-u>LeaderfMru<CR>
    nnoremap fh :<C-u>LeaderfHistorySearch<CR>
    nnoremap fg :<C-u>CtrlSF
```

### Describe your question, feature request, or bug.
run LeaderfLine after syntax off, it make a error.

### Steps to reproduce
vim test.c
:syntax off
:LeaderfLine

### Actual behaviour
```
searching ...                                                                                                                                                                      
Error detected while processing function leaderf#Line#startExpl[2]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/fcying/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 744, in startExplorer
    self._getInstance().enterBuffer(win_pos)
  File "/home/fcying/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/instance.py", line 201, in enterBuffer
    self._after_enter()
  File "/home/fcying/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/lineExpl.py", line 105, in _afterEnter
    id = int(lfEval('''matchadd('Lf_hl_lineLocation', '\t\zs\[.*:\d\+ \d\+]$')'''))
vim.error: Vim:E28: No such highlight group name: Lf_hl_lineLocation
Error detected while processing function leaderf#Line#startExpl:
line    2:
E171: Missing :endif

```
### Expected behaviour
work fine

**Comment by Yggdroot** [comment]
Fixed.

**Comment by fcying** [comment]
it work now, thanks
