### ISSUE TITLE
BUG: can't find package pt::pgen

### ISSUE THREAD

**Issue by sillybun** [Yggdroot/LeaderF#168]
- vim or neovim?
    - [x] vim
    - [ ] neovim
- `vim --version` or `nvim --version`:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 24 2018 08:30:22)
macOS version
Included patches: 1-1633
Compiled by travis@Traviss-Mac-913.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_netterm     +tag_binary
+arabic            +file_in_path      +mouse_sgr         +tag_old_static
+autocmd           +find_in_path      -mouse_sysmouse    -tag_any_white
-autoservername    +float             +mouse_urxvt       -tcl
+balloon_eval      +folding           +mouse_xterm       +termguicolors
+balloon_eval_term -footer            +multi_byte        +terminal
+browse            +fork()            +multi_lang        +terminfo
++builtin_terms    +fullscreen        -mzscheme          +termresponse
+byte_offset       -gettext           +netbeans_intg     +textobjects
+channel           -hangul_input      +num64             +timers
+cindent           +iconv             +odbeditor         +title
+clientserver      +insert_expand     +packages          +toolbar
+clipboard         +job               +path_extra        +transparency
+cmdline_compl     +jumplist          +perl/dyn          +user_commands
+cmdline_hist      +keymap            +persistent_undo   +vertsplit
+cmdline_info      +lambda            +postscript        +virtualedit
+comments          +langmap           +printer           +visual
+conceal           +libcall           +profile           +visualextra
+cryptv            +linebreak         +python/dyn        +viminfo
+cscope            +lispindent        +python3/dyn       +vreplace
+cursorbind        +listcmds          +quickfix          +wildignore
+cursorshape       +localmap          +reltime           +wildmenu
+dialog_con_gui    +lua/dyn           +rightleft         +windows
+diff              +menu              +ruby/dyn          +writebackup
+digraphs          +mksession         +scrollbind        -X11
+dnd               +modify_fname      +signs             -xfontset
-ebcdic            +mouse             +smartindent       +xim
+emacs_tags        +mouseshape        +startuptime       -xpm
+eval              +mouse_dec         +statusline        -xsmp
+ex_extra          -mouse_gpm         -sun_workshop      -xterm_clipboard
+extra_search      -mouse_jsbterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.16/darwin-thread-multi-2level/CORE 
```

- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`:
1 
- Output of `:echo &pythondll`(only vim, not neovim): 
`/System/Library/Frameworks/Python.framework/Versions/2.7/Python`
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
`/System/Library/Frameworks/Python.framework/Versions/3.6/Python`
- Output of `:py print(sys.version)`: 
```
E836: This Vim cannot execute :python after using :py3
E263: Sorry, this command is disabled, the Python library could not be loaded
```
- Output of `:py3 print(sys.version)`: 
```
3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
Bundle 'Yggdroot/LeaderF'
```
### Describe your question, feature request, or bug.
Every time I press `<leader>F` i.e. run the `:LeaderFile` command in a dictionary without `.git` . Vim will encontour an error.

### Steps to reproduce
Just run `:LeaderFile` in the home dictionary
### Actual behaviour

Error message:

```
Error detected while processing function leaderf#File#startExpl[2]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/zhangyiteng/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 630, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/Users/zhangyiteng/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 786, in startExplorer
    self.input(content)
  File "/Users/zhangyiteng/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 47, in deco
    func(self, *args, **kwargs)
  File "/Users/zhangyiteng/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 836, in input
    for cmd in self._cli.input(partial(self.setContent, content)):
  File "/Users/zhangyiteng/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/cli.py", line 26, in deco
    for i in func(*args, **kwargs):
  File "/Users/zhangyiteng/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/cli.py", line 326, in input
    if lfEval("g:Lf_CursorBlink") == '1' and callback() == False:
  File "/Users/zhangyiteng/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 798, in setContent
    for i, line in enumerate(itertools.islice(content, 10)):
  File "/Users/zhangyiteng/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/asyncExecutor.py", line 80, in read
    raise Exception(lfBytes2Str(err, encoding))
Exception: can't find package pt::pgen 1.0.3
    while executing
"package require pt::pgen 1.0.3"
    (file "/usr/local/bin/pt" line 14)
```
### Expected behaviour
No error. lol

**Comment by Yggdroot** [comment]
It is clear that this is an issue of pt，you can use rg instead.
