### ISSUE TITLE
调用leaderf时候出现bug

### ISSUE THREAD

**Issue by cxhy** [Yggdroot/LeaderF#172]
- vim or neovim?
    - [ ] vim
用的是vim
    - [ ] neovim
- `vim --version` or `nvim --version`:
vim8.1
- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
啥也没有
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
啥也没有
- Output of `:py print(sys.version)`: 
sorry the command is not available in this version
- Output of `:py3 print(sys.version)`: 
3.6.4 (default, Apr 10 2018, 15:16:17)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
- Operating system: 
    - [ ] Linux
Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
把leaderf文件解压放在~/.vim/plugged/leaderf文件夹下面，
使用vim-plug本地管理模式
call plug#begin('~/.vim/plugged')
  Plug '~/.vim/plugged/LeaderF-master'
call plug#end()
### Describe your question, feature request, or bug.
使用的最新版本的vim安装在公司服务器的本地目录里面。8.1版本的vim，编译的时候选择支持python3但是没有选择python。python2安装的是2.6.15,在本地目录，python3安装的是3.6.4，也安装在本地目录

调出leaderf的时候状态栏出现
Error detected while processing ~/.vim/plugged/LeaderF-master/autoload/laederf/File.vim:
 file <"string"> line 1 in <module>
Traceback (most recent call last)
file ........fileExpl.py line14
    from .manager inport *
file .......maanger.py line12
    from .cli import LfCli
file ......cli.py
    from datetime import datetime
file ......datetime.py
    import math as _math
ImportError      /Python-3.6.4/lib-dynload/math.cpython-26m-x86 64-linux-gnu.so:undefine sympol: Pylong
Error detected while processing function leaderf#file#startExpl[2]..leaderf#LfPy

Traceback 
  file <"string"> line 1 in <module>
NameError name fileExplManager is not defined

   
之前一直都可以正常工作，但是后来依赖的别人账户下的python环境被删掉了，然后我这边重新安装了2和3的python，再重新编译vim之后，还是存在这个问题

**Comment by Yggdroot** [comment]
`vim --version`
输出是什么

**Comment by cxhy** [comment]
https://github.com/cxhy/pic/blob/master/WechatIMG11.jpeg
装在公司服务器上面，我没法都复制出来

**Comment by cxhy** [comment]
你还需要我提供啥？

**Comment by Yggdroot** [comment]
这个问题跟LeaderF应该没关系，因为你直接`:py3 from datetime import datetime`应该也会有错。也许是没有编译好，也许电脑上有几个版本的Python，库链接错了，也许别的原因，你可以google来解决。

**Comment by jaenqi1987** [comment]
我用快捷键打开文件时遇到如下问题：



处理 function leaderf#Any#start[4]..leaderf#LfPy 时发生错误:  
第    1 行:                                                                                                                                                     Traceback (most recent call last):                                                                                                                                File "<string>", line 1, in <module>                                                                                                                            File "C:\Program Files\Vim\plugged\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 812, in start                                                        the_args.start(arguments, *args, **kwargs)                                                                                                                    File "C:\Program Files\Vim\plugged\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 744, in _default_action                                              manager.startExplorer(win_pos[2:], *args, **kwargs)                                                                                                           File "C:\Program Files\Vim\plugged\LeaderF\autoload\leaderf\python\leaderf\fileExpl.py", line 808, in startExplorer                                               super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)                                                                                          File "C:\Program Files\Vim\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 2128, in startExplorer                                               content = self._getExplorer().getContent(*args, **kwargs)                                                                                                     File "C:\Program Files\Vim\plugged\LeaderF\autoload\leaderf\python\leaderf\fileExpl.py", line 623, in getContent                                                  self._content = self._getFilesFromCache()                                                                                                                     File "C:\Program Files\Vim\plugged\LeaderF\autoload\leaderf\python\leaderf\fileExpl.py", line 42, in deco                                                         content = func(*args, **kwargs)                                                                                                                               File "C:\Program Files\Vim\plugged\LeaderF\autoload\leaderf\python\leaderf\fileExpl.py", line 538, in _getFilesFromCache                                          with lfOpen(self._cache_index, 'r+', errors='ignore') as f:                                                                                                   File "C:\Program Files\Vim\plugged\LeaderF\autoload\leaderf\python\leaderf\utils.py", line 27, in lfOpen                                                          return open(file, mode, buffering, encoding, errors, newline, closefd)                                                                                      PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Vim\\cache\\.LfCache\\python3\\file\\cacheIndex'                                             请按 ENTER 或其它命令继续

**Comment by Yggdroot** [comment]
@jaenqi1987 cache所在位置默认是$home，是你把它改了吧，改到一个权限不够的地方去了。

**Comment by jaenqi1987** [comment]
我换了个路径还是不行

**Comment by Yggdroot** [comment]
让它是默认设置不行吗

**Comment by jaenqi1987** [comment]
> 让它是默认设置不行吗

可以了，我把所有的插件重新安装了下就好了！
不过另外有个问题，nnoremap <silent> <Leader>rg :Leaderf rg<CR>  这是我设置的查找快捷键；
我看网上说这LeaderF这个插件秒杀grep等，但是我再搜索的时候发现得到的结果不太好，这个需要配置其他什么参数吗？
如果我所有validMessageId，结果含有va, mess等相关字母的所有单词都会搜索出来。

**Comment by Yggdroot** [comment]
@jaenqi1987 建议搜索使用类似如下例子的方式：
```vim
let g:Lf_RgConfig = [
        \ "--max-columns=150",
        \ "--type-add web:*.{html,css,js}*",
        \ "--glob=!git/*",
        \ "--hidden"
    \ ]

" search word under cursor, the pattern is treated as regex, and enter normal mode directly
noremap <C-F> :<C-U><C-R>=printf("Leaderf! rg -e %s ", expand("<cword>"))<CR>

" search word under cursor, the pattern is treated as regex,
" append the result to previous search results.
noremap <C-G> :<C-U><C-R>=printf("Leaderf! rg --append -e %s ", expand("<cword>"))<CR>

" search word under cursor literally only in current buffer
noremap <C-B> :<C-U><C-R>=printf("Leaderf! rg -F --current-buffer -e %s ", expand("<cword>"))<CR>

" search word under cursor literally in all listed buffers
noremap <C-D> :<C-U><C-R>=printf("Leaderf! rg -F --all-buffers -e %s ", expand("<cword>"))<CR>

" search visually selected text literally, don't quit LeaderF after accepting an entry
xnoremap gf :<C-U><C-R>=printf("Leaderf! rg -F --stayOpen -e %s ", leaderf#Rg#visual())<CR>

" recall last search. If the result window is closed, reopen it.
noremap go :<C-U>Leaderf! rg --recall<CR>


" search word under cursor in *.h and *.cpp files.
noremap <Leader>a :<C-U><C-R>=printf("Leaderf! rg -e %s -g *.h -g *.cpp", expand("<cword>"))<CR>
" the same as above
noremap <Leader>a :<C-U><C-R>=printf("Leaderf! rg -e %s -g *.{h,cpp}", expand("<cword>"))<CR>

" search word under cursor in cpp and java files.
noremap <Leader>b :<C-U><C-R>=printf("Leaderf! rg -e %s -t cpp -t java", expand("<cword>"))<CR>

" search word under cursor in cpp files, exclude the *.hpp files
noremap <Leader>c :<C-U><C-R>=printf("Leaderf! rg -e %s -t cpp -g !*.hpp", expand("<cword>"))<CR>
```

而不是`Leaderf rg`, 然后输入字符，这样是模糊匹配。

**Comment by SnowWong** [comment]
> > 让它是默认设置不行吗
> 
> 可以了，我把所有的插件重新安装了下就好了！ 不过另外有个问题，nnoremap rg :Leaderf rg 这是我设置的查找快捷键； 我看网上说这LeaderF这个插件秒杀grep等，但是我再搜索的时候发现得到的结果不太好，这个需要配置其他什么参数吗？ 如果我所有validMessageId，结果含有va, mess等相关字母的所有单词都会搜索出来。

插件不都是直接复制进home/.vim文件夹下吗？你是怎么重新安装，我用的是公司的服务器
