### ISSUE TITLE
Permission denied in Windows

### ISSUE THREAD

**Issue by clouduan** [Yggdroot/LeaderF#207]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`:  VIM-8.1
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): /e/Applications/Python35/python35.dll
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
```python
处理 function leaderf#File#startExpl[2]..leaderf#LfPy 时发生错误:
第    1 行:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Users\clouduan\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\fileExpl.py", line 667, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "c:\Users\clouduan\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 813, in startExplorer
    self.input(content)
  File "c:\Users\clouduan\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 47, in deco
    func(self, *args, **kwargs)
  File "c:\Users\clouduan\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 863, in input
    for cmd in self._cli.input(partial(self.setContent, content)):
  File "c:\Users\clouduan\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\cli.py", line 26, in deco
    for i in func(*args, **kwargs):
  File "c:\Users\clouduan\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\cli.py", line 326, in input
    if lfEval("g:Lf_CursorBlink") == '1' and callback() == False:
  File "c:\Users\clouduan\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 825, in setContent
    for i, line in enumerate(itertools.islice(content, 10)):
  File "c:\Users\clouduan\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\asyncExecutor.py", line 87, in read
    raise Exception(lfBytes2Str(err, encoding))
Exception: find: './AppData/Local/Microsoft/Windows/INetCache/Low/Content.IE5': Permission denied
```
趁现在再提个 Issue 吧，虽然你很忙。
同样是 vim in git bash 的小问题，就是遇到这种无访问权限的文件就不要报错了，自动跳过去最好。否则又要手动修改文件夹的权限了。

**Comment by Yggdroot** [comment]
把这里改改试一下：
https://github.com/Yggdroot/LeaderF/blob/910b4c8e50383b705e3b46c95cd011f89f280523/autoload/leaderf/python/leaderf/fileExpl.py#L351-L354

如果没问题我就不分Windows和Linux了。

**Comment by clouduan** [comment]
请问应该怎么改，改成这样吗
```python
 if os.name == 'nt': 
     redir_err = " 2>/dev/null" 
 else: 
     redir_err = " 2>/dev/null" 
```
这样子我试了下不行，虽然是 bash，python 并不会在 bash 环境中执行，所以没法重定向

**Comment by Yggdroot** [comment]
哦，我忘记以前为什么区分Windows和Linux了，可能以前就遇到这个问题。

建议使用rg，毕竟Windows上使用Linux下的find不太专业。

**Comment by clouduan** [comment]
OK
