### ISSUE TITLE
Undefined variable: g:Lf_MruCacheFileName when calling LeaderfMru

### ISSUE THREAD

**Issue by joshua7v** [Yggdroot/LeaderF#210]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 

```
NVIM v0.3.1-156-g0ed8b12
Build type: Release
LuaJIT 2.0.5
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/Users/travis/build/neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@Traviss-Mac-1284.local

Features: +acl +iconv -jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:py3 print(sys.version)`: 

```
3.6.3 (default, Aug 17 2018, 13:09:04)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

```
call dein#add('Yggdroot/LeaderF', {
      \'build': './install.sh',
      \'on_cmd': ['LeaderfFile', 'LeaderfMru', 'LeaderfMruCwd', 'LeaderfBufferAll', 'LeaderfBufTag', 'LeaderfFunctionAll', 'LeaderfLine']
      \})
```

### Describe your question, feature request, or bug.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/joshua/.config/nvim/plugged/repos/github.com/Yggdroot/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 771, in startExplorer
    content = self._getExplorer().getContent(*args, **kwargs)
  File "/Users/joshua/.config/nvim/plugged/repos/github.com/Yggdroot/LeaderF/autoload/leaderf/python/leaderf/mruExpl.py", line 23, in getContent
    mru.saveToCache(lfEval("readfile(g:Lf_MruCacheFileName)"))
  File "/Users/joshua/erinn/asdf/installs/python/3.6.3/lib/python3.6/site-packages/neovim/plugin/script_host.py", line 204, in eval
    obj = self.request("vim_eval", expr)
  File "/Users/joshua/erinn/asdf/installs/python/3.6.3/lib/python3.6/site-packages/neovim/api/nvim.py", line 170, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/joshua/erinn/asdf/installs/python/3.6.3/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 100, in request
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b'Vim:E121: Undefined variable: g:Lf_MruCacheFileName'
```

I'm using `dein` to lazy load plugins.
The error above will appear and only appear when calling MRU related cmds (eg. LeaderfMru, LeaderfMruCwd) without calling other cmds first.

for example

after nvim started, call LeaderfMru immediately will cause the error
but if i call LeaderfFile before calling LeaderfMru, there's no such error, and everything works fine

### Steps to reproduce

1. dein config for leaderf
2. call LeaderfMru without calling LeaderfFile

**Comment by Yggdroot** [comment]
Strictly speaking, this is a bug of plugin manager plugin. Lazy loading should perform the same behavior as normal loading.

**Comment by Yggdroot** [comment]
Fixed.

**Comment by joshua7v** [comment]
awesome! this fix really helps a lot
