### ISSUE TITLE
'GtagsExplManager' object has no attribute '_cb_content' 

### ISSUE THREAD

**Issue by bstaint** [Yggdroot/LeaderF#366]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
```
处理 function leaderf#Any#start[4]..leaderf#LfPy 时发生错误:
第    1 行:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Portable\gVim\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 715, in start
    the_args.start(arguments, *args, **kwargs)
  File "D:\Portable\gVim\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 671, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "D:\Portable\gVim\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\gtagsExpl.py", line 1058, in startExplorer
    super(GtagsExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "D:\Portable\gVim\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 1474, in startExplorer
    self._bangEnter()
  File "D:\Portable\gVim\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\gtagsExpl.py", line 1005, in _bangEnter
    self._workInIdle(bang=True)
  File "D:\Portable\gVim\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 1604, in _workInIdle
    if self._index < cur_len or len(self._cb_content) > 0:
AttributeError: 'GtagsExplManager' object has no attribute '_cb_content'
处理 function leaderf#Any#start 时发生错误:
第    4 行:
E171: 缺少 :endif
```

### Steps to reproduce
执行: `Leaderf! gtags --cword`

**Comment by Yggdroot** [comment]
这个问题应该fix了，请试一下。

**Comment by bstaint** [comment]
已经没问题了。
