### ISSUE TITLE
Strange Error when using :LeaderFfile, only in one repo

### ISSUE THREAD

**Issue by ApolloTang** [Yggdroot/LeaderF#367]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 28 2019 01:07:30)
macOS version
Included patches: 1-1722
Compiled by travis@Traviss-Mac.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tcl
+arabic            +find_in_path      +mouse_xterm       +termguicolors
+autocmd           +float             +multi_byte        +terminal
+autochdir         +folding           +multi_lang        +terminfo
-autoservername    -footer            -mzscheme          +termresponse
+balloon_eval      +fork()            +netbeans_intg     +textobjects
+balloon_eval_term +fullscreen        +num64             +textprop
+browse            -gettext           +odbeditor         +timers
++builtin_terms    -hangul_input      +packages          +title
+byte_offset       +iconv             +path_extra        +toolbar
+channel           +insert_expand     +perl/dyn          +transparency
+cindent           +job               +persistent_undo   +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           +python/dyn        +visual
+cmdline_info      +libcall           +python3/dyn       +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          +ruby/dyn          +wildmenu
+cursorbind        +lua/dyn           +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con_gui    +mksession         +smartindent       -X11
+diff              +modify_fname      -sound             -xfontset
+digraphs          +mouse             +spell             +xim
+dnd               +mouseshape        +startuptime       -xpm
-ebcdic            +mouse_dec         +statusline        -xsmp
+emacs_tags        -mouse_gpm         -sun_workshop      -xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static    
-farsi             -mouse_sysmouse    -tag_any_white     
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE 


```
- Output of `:echo has("python")`:  `0`
- Output of `:echo has("python3")`:  `1`
- Output of `:echo &pythondll`(only vim, not neovim): 
```
/usr/local/Frameworks/Python.framework/Versions/3.7/Python
```
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
```
E113: Unknown option: pythontreedll
```
- Output of `:py print(sys.version)`: 
```
E836: This Vim cannot execute :python after using :py3
E263: Sorry, this command is disabled, the Python library could not be loaded.
```
- Output of `:py3 print(sys.version)`:
```
3.7.2 (default, Feb 12 2019, 08:15:36)
[Clang 10.0.0 (clang-1000.11.45.5)]
``` 
- Output of `:echo g:Lf_Debug_Cmd`: 
```
E121: Undefined variable: g:Lf_Debug_Cmd
```
- Output of `:echo g:Lf_FilesFromCache`: 
```
E121: Undefined variable: g:Lf_FilesFromCache
```
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
  nmap <space>p :LeaderfFile<cr>
  nmap <space>b :LeaderfBuffer<cr>
```
### Describe your question, feature request, or bug.

This error start to appear recently when I type `:LeaderfFile`
```
Error detected while processing function leaderf#File#startExpl[2]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/326937463/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 726, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/Users/326937463/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1547, in startExplorer
    self.input()
  File "/Users/326937463/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 59, in deco
    func(self, *args, **kwargs)
  File "/Users/326937463/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1740, in input
    self._guessSearch(self._content)
  File "/Users/326937463/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 896, in _guessSearch
    filter_method = partial(fuzzyEngine.guessMatch, engine=self._fuzzy_engine, filename=filename,
AttributeError: module 'fuzzyEngine' has no attribute 'guessMatch'
```

### Steps to reproduce

This only happen on a repo at work place, but all other repo is fine.
I am not sure where to look to search for my bug, any suggestion ?

**Comment by ApolloTang** [comment]
I ran install.sh and got this:
```
$ ./install.sh
Begin to compile C extension of Python2 ...
python2: realpath couldn't resolve "/usr/bin/python2"

Begin to compile C extension of Python3 ...
running build
running build_ext
building 'fuzzyMatchC' extension
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c fuzzyMatch.c -o build/temp.macosx-10.14-x86_64-3.7/fuzzyMatch.o


Agreeing to the Xcode/iOS license requires admin privileges, please run “sudo xcodebuild -license” and then retry this command.
```

So I have to update my licence:
```
sudo xcodebuild -license
```
That fixed it

Thanks for the quick response !! 


Thank you for the awesome plugin!!!
