### ISSUE TITLE
[BUG] Leaderf! --recall执行出错

### ISSUE THREAD

**Issue by x1314aq** [Yggdroot/LeaderF#411]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 0.4.3
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.8.0
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Steps to reproduce

1. 使用gtags生成tags
2. 执行`Leaderf gtags --all`
3. 执行`Leaderf! --recall`

### Actual behaviour
```
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy[1]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.nvim/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 774, in start
    self._last_cmd(arguments, *args, **kwargs)
  File "/root/.nvim/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 701, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/root/.nvim/LeaderF/autoload/leaderf/python/leaderf/gtagsExpl.py", line 1139, in startExplorer
    super(GtagsExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/root/.nvim/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1963, in startExplorer
    self._bangEnter()
  File "/root/.nvim/LeaderF/autoload/leaderf/python/leaderf/gtagsExpl.py", line 1083, in _bangEnter
    instance.window.options["cursorline"] = True
AttributeError: 'FloatWindow' object has no attribute 'options'
```
### Expected behaviour
python3不会报错

**Comment by Yggdroot** [comment]
修好了。
