### ISSUE TITLE
Popup not working

### ISSUE THREAD

**Issue by HuanGong** [Yggdroot/LeaderF#416]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`:  all
- Output of `:echo has("python")`:  1
- Output of `:echo has("python3")`:  1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 2.7.6 
- Output of `:py3 print(sys.version)`:  3.6.1
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
  let g:Lf_ShortcutF = '<C-P>'
  let g:Lf_WindowPosition = 'popup'
  if executable("rg")
    " search word under cursor, the pattern is treated as regex, and enter normal mode directly
    noremap <leader>fc :<C-U><C-R>=printf("Leaderf! rg -e %s ", expand("<cword>"))<CR>
    " search word under cursor, the pattern is treated as regex,
    " append the result to previous search results.
    noremap <leader>fg :<C-U><C-R>=printf("Leaderf! rg --append -e %s ", expand("<cword>"))<CR>
    " search word under cursor literally only in current buffer
    noremap <leader>fb :<C-U><C-R>=printf("Leaderf! rg -F --current-buffer -e %s ", expand("<cword>"))<CR>
    " search visually selected text literally, don't quit LeaderF after accepting an entry
    xnoremap <leader>fv :<C-U><C-R>=printf("Leaderf! rg -F --stayOpen -e %s ", leaderf#Rg#visual())<CR>
    " recall last search. If the result window is closed, reopen it.
    noremap <leader>go :<C-U>Leaderf! rg --stayOpen --recall<CR>
  else
    set wildchar=<Tab> wildmenu wildmode=full
    nnoremap <leader>fd :AsyncRun grep -rwn <cword> .
    nnoremap <leader>fc :AsyncRun grep -rwn <cword> .<cr>
  endif

### Describe your question, feature request, or bug.
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy[1]..provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gh/.vim/Plug/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 770, in start
    the_args.start(arguments, *args, **kwargs)
  File "/home/gh/.vim/Plug/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 701, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/home/gh/.vim/Plug/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 729, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/home/gh/.vim/Plug/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1920, in startExplorer
    self._getInstance().enterBuffer(win_pos, not isinstance(content, list))
  File "/home/gh/.vim/Plug/LeaderF/autoload/leaderf/python/leaderf/instance.py", line 880, in enterBuffer
    self._createPopupWindow(clear)
  File "/home/gh/.vim/Plug/LeaderF/autoload/leaderf/python/leaderf/instance.py", line 327, in _createPopupWindow
    buf_number = int(lfEval("bufadd('{}')".format(escQuote(self._buffer_name))))
  File "/usr/lib/python3.6/site-packages/pynvim/plugin/script_host.py", line 203, in eval
    obj = self.request("vim_eval", expr)
  File "/usr/lib/python3.6/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.nvim.NvimError: b'Vim:E117: Unknown function: bufadd'

**Comment by Yggdroot** [comment]
popup feature requires nvim0.4.2+.
