### ISSUE TITLE
Error when g:Lf_WindowPosition = 'popup'

### ISSUE THREAD

**Issue by fatjing** [Yggdroot/LeaderF#435]
- vim or neovim? 
    - [x] vim 8.2.12
    - [ ] neovim
- Output of `:echo g:Lf_Debug_Cmd`: ```
rg --no-messages --files   -g "!node_modules" -g "!*.sw?" -g "!~$*" -g "!*.bak" -g "!*.exe" -g "!*.o" -g "!*.so" -g "!*.py[co]"    "C:\Users\fatjing\Programs\Vim\vim82"``` 
- Output of `:echo g:Lf_FilesFromCache`: 1
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```let g:Lf_WindowPosition = 'popup'```
I've tested with only this line written in vimrc, if this line is removed everything works fine

### Steps to reproduce
Start gvim from C:\Users\fatjing\Programs\Vim\vim82
Run ```:Leaderf file```

### Actual behaviour
Got error:
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\fatjing\Programs\Vim\vimfiles\pack\bundle\start\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 780, in start
    the_args.start(arguments, *args, **kwargs)
  File "C:\Users\fatjing\Programs\Vim\vimfiles\pack\bundle\start\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 712, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "C:\Users\fatjing\Programs\Vim\vimfiles\pack\bundle\start\LeaderF\autoload\leaderf\python\leaderf\fileExpl.py", line 729, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "C:\Users\fatjing\Programs\Vim\vimfiles\pack\bundle\start\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 2001, in startExplorer
    self._getInstance().enterBuffer(win_pos, not isinstance(content, list))
  File "C:\Users\fatjing\Programs\Vim\vimfiles\pack\bundle\start\LeaderF\autoload\leaderf\python\leaderf\instance.py", line 902, in enterBuffer
    self._createPopupWindow(clear)
  File "C:\Users\fatjing\Programs\Vim\vimfiles\pack\bundle\start\LeaderF\autoload\leaderf\python\leaderf\instance.py", line 487, in _createPopupWindow
    lfCmd("call win_execute(%d, 'setlocal filetype=leaderf')" % self._popup_winid)
vim.error: Vim(redir):E930: Cannot use :redir inside execute()
Error detected while processing function leaderf#Any#start:
line    4:
E171: Missing :endif
```

**Comment by Yggdroot** [comment]
This issue is similar with #408 , to see which plugin is conflict with LeaderF.

**Comment by fatjing** [comment]
Thanks for the information.
I tried disabling plugin one by one and it seems that tpope/vim-sleuth is causing the problem

**Comment by Yggdroot** [comment]
fixed.

**Comment by zzzzzzmj** [comment]
小弟发现`prabirshrestha/async.vim` 也会与leaderf使用popup有冲突

**Comment by Yggdroot** [comment]
> 小弟发现`prabirshrestha/async.vim` 也会与leaderf使用popup有冲突

I have already fixed the issue, did you use the lastest version of leaderf?

**Comment by zzzzzzmj** [comment]
更新了最新还是有同样的问题，详情 [#444](https://github.com/Yggdroot/LeaderF/issues/444)

**Comment by Yggdroot** [comment]
> 更新了最新还是有同样的问题，详情 [#444](https://github.com/Yggdroot/LeaderF/issues/444)

it is a different issue, this issue is e930 and yours is e344.
