### ISSUE TITLE
:Leaderf file等相关命令报错

### ISSUE THREAD

**Issue by anywho** [Yggdroot/LeaderF#437]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 07 2019 15:35:43)
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): E113: Unknown option: pythonthreedll
E15: Invalid expression: &pythonthreedll
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.5.2 (default, Oct  8 2019, 13:06:37)
[GCC 5.4.0 20160609]
- Output of `:echo g:Lf_Debug_Cmd`: E121: Undefined variable: g:Lf_Debug_Cmd
E15: Invalid expression: g:Lf_Debug_Cmd
- Output of `:echo g:Lf_FilesFromCache`: E121: Undefined variable: g:Lf_FilesFromCache
E15: Invalid expression: g:Lf_FilesFromCache
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: not use

### Describe your question, feature request, or bug.
使用:Leaderf file等相关命令时就会报错，错误信息如下，相同的.vimrc配置文件在ubuntu本地虚拟机上不会出问题，但是这份配置文件配置在Ubuntu远程服务器，当我ssh登录使用vim时就会出问题。
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:                                                                                                                      
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/whx/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 780, in start
    the_args.start(arguments, *args, **kwargs)
  File "/home/whx/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 712, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/home/whx/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 729, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/home/whx/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1975, in startExplorer
    self._getInstance().enterBuffer(win_pos, not isinstance(content, list))
  File "/home/whx/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/instance.py", line 894, in enterBuffer
    self._setAttributes()
  File "/home/whx/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/instance.py", line 277, in _setAttributes
    lfCmd("setlocal signcolumn=no")
vim.error: Vim(setlocal):E518: Unknown option: signcolumn=no
Error detected while processing function leaderf#Any#start:
line    4:
E171: Missing :endif

**Comment by Yggdroot** [comment]
vim太旧了。

**Comment by Yggdroot** [comment]
signcolumn 是7.4.2201才加的，理论上LeaderF只要是vim7.4.330+就可以，所以fix这个issue。
