### ISSUE TITLE
LeaderfFile出現錯誤

### ISSUE THREAD

**Issue by chin33z** [Yggdroot/LeaderF#45]
執行:LeaderfFile會出現如下錯誤.

```
處理 /home/dhu/.vim/plugged/LeaderF/autoload/leaderf.vim 時發生錯誤:
行   13:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dhu/.vim/plugged/LeaderF/autoload/leaderf/bufExpl.py", line 26
    buffers = {b.number: b for b in vim.buffers
                             ^
SyntaxError: invalid syntax
處理 function leaderf#startFileExpl..leaderf#LfPy 時發生錯誤:
行    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dhu/.vim/plugged/LeaderF/autoload/leaderf/manager.py", line 549, in startExplorer
    self._getInstance().enterBuffer(win_pos)
  File "/home/dhu/.vim/plugged/LeaderF/autoload/leaderf/manager.py", line 141, in _getInstance
    self._afterExit)
  File "/home/dhu/.vim/plugged/LeaderF/autoload/leaderf/instance.py", line 36, in __init__
    self._initStlVar()
  File "/home/dhu/.vim/plugged/LeaderF/autoload/leaderf/instance.py", line 40, in _initStlVar
    lfCmd("let g:Lf_{}_StlCategory = '-'".format(self._category))
ValueError: zero length field name in format
```

**Comment by Yggdroot** [comment]
怎麼出現的？是每次都是出現還是在某種情況下會出現。
能否給出reproduce的步驟？

**Comment by chin33z** [comment]
每次都會,但是在我的某台server上才會. 另一台不會.
我猜可能是環境的設定不太一樣.

**Comment by Yggdroot** [comment]
既然每次都会，问题应该很好查。能否给一些更详细的信息？

**Comment by chin33z** [comment]
這是執行失敗的server上的vim設定
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 24 2015 02:23:23)
引入修正: 1-207, 209-629
修改者為<bugzilla@redhat.com>
編譯者:<bugzilla@redhat.com>
超強版本 不使用圖型界面。 目前可使用(+)與不可使用(-)的模組列表:
+acl             +conceal         +farsi           +libcall         +mouse_netterm   +profile         +syntax          +visualextra
+arabic          +cryptv          +file_in_path    +linebreak       +mouse_sgr       +python/dyn      +tag_binary      +viminfo
+autocmd         +cscope          +find_in_path    +lispindent      -mouse_sysmouse  -python3         +tag_old_static  +vreplace
-balloon_eval    +cursorbind      +float           +listcmds        +mouse_urxvt     +quickfix        -tag_any_white   +wildignore
-browse          +cursorshape     +folding         +localmap        +mouse_xterm     +reltime         -tcl             +wildmenu
++builtin_terms  +dialog_con      -footer          -lua             +multi_byte      +rightleft       +terminfo        +windows
+byte_offset     +diff            +fork()          +menu            +multi_lang      -ruby            +termresponse    +writebackup
+cindent         +digraphs        +gettext         +mksession       -mzscheme        +scrollbind      +textobjects     -X11
-clientserver    -dnd             -hangul_input    +modify_fname    +netbeans_intg   +signs           +title           -xfontset
-clipboard       -ebcdic          +iconv           +mouse           +path_extra      +smartindent     -toolbar         -xim
+cmdline_compl   +emacs_tags      +insert_expand   -mouseshape      +perl            -sniff           +user_commands   -xsmp
+cmdline_hist    +eval            +jumplist        +mouse_dec       +persistent_undo +startuptime     +vertsplit       -xterm_clipboard
+cmdline_info    +ex_extra        +keymap          +mouse_gpm       +postscript      +statusline      +virtualedit     -xterm_save
+comments        +extra_search    +langmap         -mouse_jsbterm   +printer         -sun_workshop    +visual          -xpm
        系統 vimrc 設定檔: "/etc/vimrc"
  使用者個人 vimrc 設定檔: "$HOME/.vimrc"
    第二組個人 vimrc 檔案: "~/.vim/vimrc"
   使用者個人 exrc 設定檔: "$HOME/.exrc"
              $VIM 預設值: "/etc"
       $VIMRUNTIME 預設值: "/usr/share/vim/vim74"
編譯方式: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -g -pipe -Wall -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=gen
eric -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
鏈結方式: gcc   -Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lnsl  -lselinux  -ltinfo -lacl
 -lattr -lgpm   -Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE  -fstack-protector  -L/usr/lib64/perl5/CORE -lperl -lresolv -lnsl -ldl -lm -lcrypt -
lutil -lpthread -lc
```

這是執行正常的server上的vim設定
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 30 2017 08:45:56)
引入修正: 1-525
編譯者:chris@tpe-dev-l2
超強版本 使用 GTK2 圖型界面。 目前可使用(+)與不可使用(-)的模組列表:
+acl             +conceal         +file_in_path    +libcall         +mouse_sgr       +profile         +tag_old_static  +viminfo
+arabic          +cryptv          +find_in_path    +linebreak       -mouse_sysmouse  +python          -tag_any_white   +vreplace
+autocmd         +cscope          +float           +lispindent      +mouse_urxvt     -python3         -tcl             +wildignore
+balloon_eval    +cursorbind      +folding         +listcmds        +mouse_xterm     +quickfix        +termguicolors   +wildmenu
+browse          +cursorshape     -footer          +localmap        +multi_byte      +reltime         +terminfo        +windows
++builtin_terms  +dialog_con_gui  +fork()          -lua             +multi_lang      +rightleft       +termresponse    +writebackup
+byte_offset     +diff            +gettext         +menu            -mzscheme        -ruby            +textobjects     +X11
+channel         +digraphs        -hangul_input    +mksession       +netbeans_intg   +scrollbind      +timers          -xfontset
+cindent         +dnd             +iconv           +modify_fname    +num64           +signs           +title           +xim
+clientserver    -ebcdic          +insert_expand   +mouse           +packages        +smartindent     +toolbar         -xpm
+clipboard       +emacs_tags      +job             +mouseshape      +path_extra      +startuptime     +user_commands   +xsmp_interact
+cmdline_compl   +eval            +jumplist        +mouse_dec       -perl            +statusline      +vertsplit       +xterm_clipboard
+cmdline_hist    +ex_extra        +keymap          -mouse_gpm       +persistent_undo -sun_workshop    +virtualedit     -xterm_save
+cmdline_info    +extra_search    +lambda          -mouse_jsbterm   +postscript      +syntax          +visual
+comments        +farsi           +langmap         +mouse_netterm   +printer         +tag_binary      +visualextra
        系統 vimrc 設定檔: "$VIM/vimrc"
  使用者個人 vimrc 設定檔: "$HOME/.vimrc"
    第二組個人 vimrc 檔案: "~/.vim/vimrc"
   使用者個人 exrc 設定檔: "$HOME/.exrc"
         系統 gvimrc 檔案: "$VIM/gvimrc"
     使用者個人 gvimrc 檔: "$HOME/.gvimrc"
   第二組個人 gvimrc 檔案: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
           系統選單設定檔: "$VIMRUNTIME/menu.vim"
              $VIM 預設值: "/usr/local/share/vim"
編譯方式: /opt/rh/devtoolset-3/root/usr/bin/gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib64/
gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -
I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12     -g -O2 -U_FORTIFY_SOURCE -D_FORTIF
Y_SOURCE=1
鏈結方式: /opt/rh/devtoolset-3/root/usr/bin/gcc   -ltinfo -L/usr/local/lib -Wl,--as-needed -o vim   -pthread -lgtk-x11-2.0 -lgdk-x11-2.0 -la
tk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lgmodule-2.0 -l
gthread-2.0 -lrt -lglib-2.0   -lSM -lICE -lXt -lX11 -lSM -lICE  -lm -ltinfo -lelf -lnsl  -lselinux  -lacl -lattr -ldl    -L/usr/local/lib/py
thon2.7/config/ -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic
```

**Comment by Yggdroot** [comment]
我想应该是的，`SyntaxError: invalid syntax`, 应该是说2.6不支持那样的语法。这个插件是需要Python2.7+的。

**Comment by chin33z** [comment]
瞭解, 謝謝
