### ISSUE TITLE
Completely broken (sign not allowed in string fomat)

### ISSUE THREAD

**Issue by eyalk5** [Yggdroot/LeaderF#495]
- vim or neovim? 
    - [ ] vim
    - [x ] neovim
- Output of `vim --version` or `nvim --version`: 
v.5.0-295 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
3.7.0

- Operating system: 
    - [ ] Linux
    - [ X] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
let g:Lf_PreviewInPopup =1
let g:Lf_PopupHeight =0.6
let g:Lf_PopupWidth =0.8
let g:Lf_WindowPosition = 'popup'
let g:Lf_PopupPosition=[float2nr(&lines * 0.5),1]

### Describe your question, feature request, or bug.
Everytime I try to use LeaderF I get this: 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/eyalkarni/vimpy3/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 356, in _previewResult
    self._cli.buildPopupPrompt()
  File "/Users/eyalkarni/vimpy3/plugged/LeaderF/autoload/leaderf/python/leaderf/cli.py", line 314, in buildPopupPrompt
    self._buildPopupPrompt()
  File "/Users/eyalkarni/vimpy3/plugged/LeaderF/autoload/leaderf/python/leaderf/cli.py", line 235, in _buildPopupPrompt
    part3_width=len(part3))
ValueError: Sign not allowed in string format specifier
```

And it opens in a state where it doesn't function. 

It is probably because there is no underflow check in there: 

```
part3_start = input_win_width - len(part3) - 2
        sep2_start = part3_start - len(sep)
        part2_start = sep2_start - 2 - len(part2)
        sep1_start = part2_start - len(sep)
        spin_start = sep1_start - 1 - len(spin)
        part1_width = spin_start - 1
```

### Steps to reproduce
do anything with leaderf (line/mru/buffer)

**Comment by eyalk5** [comment]
```
        text = "{:<{part1_width}} {} {:>{sep_width}} {:>{part2_width}} {:>{sep_width}} {:>{part3_width}} ".format(part1,
                                                                                                                  spin,
                                                                                                                  sep,
                                                                                                                  part2,
                                                                                                                  sep,
                                                                                                                  part3,
                                                                                                                  sep_width=min(len(sep),1),
                                                                                                                  part1_width=part1_width,
                                                     part2_width=min(len(part2),10),                                                                                                                 part3_width=min(len(part3),10)
```
seems to fix it

**Comment by eyalk5** [comment]
Possibly, it only happens in neovim-qt. The fix I posted seems to fix it.
