### ISSUE TITLE
Error when using in  goneovim v0.44 

### ISSUE THREAD

**Issue by eyalk5** [Yggdroot/LeaderF#501]
- vim or neovim? 
    - [ ] vim
    - [X ] neovim

- Operating system: 
    - [ ] Linux
    - [ X] Mac OS X
    - [ ] Windows
    - [ ] Etc.

- Configurations related to LeaderF in vimrc: 
let g:Lf_ShowHidden  = 1
let g:Lf_MaxCount =50000
let g:Lf_PreviewInPopup =1

python 3.7.0

### Describe your question, feature request, or bug.

I keep getting this error. Only on goneovim v0.44 . It works fine on neovim-qt. 

The problem is due to 
float_win_pos = lfEval("nvim_win_get_position(%d)" % float_window.id)

I tried running it :
echo nvim_win_get_position(win_getid('%'))
Got strange results. always [1,something]. 
But maybe that is not the way to go. 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/eyalkarni/vimpy3/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 779, in start
    the_args.start(arguments, *args, **kwargs)
  File "/Users/eyalkarni/vimpy3/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 711, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/Users/eyalkarni/vimpy3/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2005, in startExplorer
    self.input()
  File "/Users/eyalkarni/vimpy3/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 56, in deco
    func(self, *args, **kwargs)
  File "/Users/eyalkarni/vimpy3/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2280, in input
    self._search(cur_content)
  File "/Users/eyalkarni/vimpy3/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 944, in _search
    self._previewResult(False)
  File "/Users/eyalkarni/vimpy3/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 367, in _previewResult
    self._previewInPopup(line)
  File "/Users/eyalkarni/vimpy3/plugged/LeaderF/autoload/leaderf/python/leaderf/lineExpl.py", line 140, in _previewInPopup
    self._createPopupPreview(vim.buffers[int(buf_number)].name, buf_number, line_nr)
  File "/Users/eyalkarni/vimpy3/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 573, in _createPopupPreview
    self._createPopupModePreview(title, buf_number, line_nr, jump_cmd)
  File "/Users/eyalkarni/vimpy3/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 462, in _createPopupModePreview
    self._preview_winid = int(lfEval("nvim_open_win(%d, 0, %s)" % (buf_number, str(config))))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pynvim/plugin/script_host.py", line 203, in eval
    obj = self.request("vim_eval", expr)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim:E5555: API call: 'height' key must be a positive Integer
```

### Steps to reproduce
type something in leaderf. 

### Actual behaviour
the messages appears. 
Leaderf is dead. 

(it only happens when preview is on)

**Comment by Yggdroot** [comment]
This maybe because `self._preview_winid = int(lfEval("nvim_open_win(%d, 0, %s)" % (buf_number, str(config))))` does not work on goneovim. If so, it is the bug of goneovim.

**Comment by akiyosi** [comment]
Hi,
Would you tell me why do you use `nivm_win_get_position()` to create popup window?
It is not good to use cursor position instead of `nvim_win_get_position()`?

BTW, I have get the comment about `nvim_win_get_position()` related with `ext_multigrid` ui attach option.
https://github.com/neovim/neovim/issues/11935#issuecomment-590894739

**Comment by Yggdroot** [comment]
I use `nivm_win_get_position()` to get the top left corner position of the float window. I know `nvim_win_get_config()` can also get the position, but `nivm_win_get_position()` is easier.
Using `nivm_win_get_position()` can get the right value in terminal neovim and neovim-qt, but it can not get the right value in goneovim, I think it is goneovim's bug.

**Comment by akiyosi** [comment]
It is not goneovim's bug.
Did you see https://github.com/neovim/neovim/issues/11935#issuecomment-590894739 ?

**Comment by Yggdroot** [comment]
how to explain nivm_win_get_position() works well in terminal neovim and neovim-qt?

**Comment by akiyosi** [comment]
This is because terminal neovim and neovim-qt based single-grid UI drawing. In single grid UI, there is only a single grid (main grid), so `nvim_win_get_position()` works effectively, but it does not work well in multi-grid based UI drawing that handles multiple grids.

@bfredl
I would like additional explanation or supplement if there is.

**Comment by Yggdroot** [comment]
Fixed.
