### ISSUE TITLE
If `g:Lf_ReverseOrder` is set, it will not work if you select in normal mode and switch to insert mode.

### ISSUE THREAD

**Issue by tamago324** [Yggdroot/LeaderF#505]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 21 2020 23:12:37)
MS-Windows 32 ビット コンソール 版
適用済パッチ: 1-140
Compiled by appveyor@APPVYR-WIN
Huge 版 without GUI.  機能の一覧 有効(+)/無効(-)
+acl                +eval               +multi_byte_ime/dyn -tag_old_static
+arabic             +ex_extra           +multi_lang         -tag_any_white
+autocmd            +extra_search       +mzscheme/dyn       +tcl/dyn
+autochdir          -farsi              -netbeans_intg      +termguicolors
+autoservername     +file_in_path       +num64              +terminal
-balloon_eval       +find_in_path       +packages           -termresponse
+balloon_eval_term  +float              +path_extra         +textobjects
-browse             +folding            +perl/dyn           +textprop
++builtin_terms     -footer             +persistent_undo    -tgetent
+byte_offset        +gettext/dyn        +popupwin           +timers
+channel            -hangul_input       -postscript         +title
+cindent            +iconv/dyn          +printer            -toolbar
+clientserver       +insert_expand      +profile            +user_commands
+clipboard          +job                +python/dyn         +vartabs
+cmdline_compl      +jumplist           +python3/dyn        +vertsplit
+cmdline_hist       +keymap             +quickfix           +virtualedit
+cmdline_info       +lambda             +reltime            +visual
+comments           +langmap            +rightleft          +visualextra
+conceal            +libcall            +ruby/dyn           +viminfo
+cryptv             +linebreak          +scrollbind         +vreplace
+cscope             +lispindent         +signs              +vtp
+cursorbind         +listcmds           +smartindent        +wildignore
+cursorshape        +localmap           +sound              +wildmenu
+dialog_con         +lua/dyn            +spell              +windows
+diff               +menu               +startuptime        +writebackup
+digraphs           +mksession          +statusline         -xfontset
-dnd                +modify_fname       -sun_workshop       -xim
-ebcdic             +mouse              +syntax             -xpm_w32
+emacs_tags         -mouseshape         +tag_binary         -xterm_save
      システム vimrc: "$VIM\vimrc"
      ユーザー vimrc: "$HOME\_vimrc"
   第2ユーザー vimrc: "$HOME\vimfiles\vimrc"
   第3ユーザー vimrc: "$VIM\_vimrc"
       ユーザー exrc: "$HOME\_exrc"
    第2ユーザー exrc: "$VIM\_exrc"
  デフォルトファイル: "$VIMRUNTIME\defaults.vim"
コンパイル: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND  -DFEAT_JOB_CHANNEL      -DWINVER=0x0501 -D_WIN32_WINNT=0
x0501 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG /arch:IA32 /Zl /MT -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_D
LL=\"tcl86t.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll
\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python38.dll\" -DFEAT_MZSCHEME -I "C:\Program Files (x86)\Racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEM
E -DDYNAMIC_MZSCH_DLL=\"libracket3m_a36fs8.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_a36fs8.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -
DDYNAMIC_PERL_DLL=\"perl528.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL=\"msvcrt-ruby240.dll\" -DRUBY_VERSION=24 -DFEAT_HUGE /Fd.\ObjCULYHTRZi386/ /Zi
リンク: link  /nologo /opt:ref /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:i386
libcmt.lib  user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python38.lib   "C:\Tcl\lib\tclstub86.lib" winmm.lib WSock32.l
ib /PDB:vim.pdb -debug
```
- Output of `:echo has("python")`: `1`
- Output of `:echo has("python3")`: `1`
- Output of `:echo &pythondll`(only vim, not neovim): `python27.dll`
- Output of `:echo &pythonthreedll`(only vim, not neovim): `python38.dll`
- Output of `:py print(sys.version)`: 

```
2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]
```

- Output of `:py3 print(sys.version)`: 
```
3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)]
```
- Output of `:echo g:Lf_Debug_Cmd`: 

```
rg --no-messages --files
```
- Output of `:echo g:Lf_FilesFromCache`:  `1`
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

An error occurs when you set `let g:Lf_ReverseOrder = 1`, select a file in normal mode of `:Leaderf file`, switch to insert mode, and try to open the file.

min_vimrc:

```vim
" C:/tmp/leaderf/min_vimrc

set encoding=utf-8
scriptencoding utf-8

syntax enable
filetype plugin indent on

set nocompatible

call plug#begin('~/vimfiles/plugged')

" Plug 'C:/tmp/leaderf/LeaderF'
Plug '~/ghq/github.com/Yggdroot/LeaderF'

call plug#end()

" no backup
set nobackup
set nowritebackup

" no swap
set noswapfile
set updatecount=0

nnoremap <silent> <Space>q :<C-u>quit<CR>
nnoremap <silent> <Space>Q :<C-u>quit!<CR>

let g:Lf_ReverseOrder = 1

let g:Lf_HideHelp = 1

let g:Lf_WindowHeight = 10
```

### Steps to reproduce

Get files, starting Vim.

```
cd C:/tmp/leaderf
git clone git@github.com:Yggdroot/LeaderF.git

gvim.exe -u min_vimrc
```

Run LeaderF

```
:Leaderf! file
s
<Tab>
<CR>
```

1. execute `:Leaderf! file`.
1. Select files in normal mode (`s`)
1. Switch to insert mode (`<Tab>`)
1. `<CR>`

### Actual behaviour

I get the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\user1\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 57, in deco
    func(self, *args, **kwargs)
  File "C:\Users\user1\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 2340, in input
    if self.accept() is None:
  File "C:\Users\user1\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 1657, in accept
    files.append(self._getInstance().buffer[i-1])
IndexError: list index out of range
```

### Expected behaviour

Even when `let g:Lf_ReverseOrder = 1` is set, correctly select multiple files and open the files.

**Comment by tamago324** [comment]
Thanks!
