### ISSUE TITLE
command :LeaderfFile fails

### ISSUE THREAD

**Issue by etorth** [Yggdroot/LeaderF#509]
I have this map to reuse the ctrlp keybind:
`n  <C-P>       * :<C-U>LeaderfFile<CR>`
But when I use it, it fails as:
```
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/lan/cva/debugger_user5/anhong/.remote_config/configure/.vim/bundle/LeaderF-master/autoload/leaderf/python/leaderf/anyExpl.py", line 779, in start
    the_args.start(arguments, *args, **kwargs)
  File "/lan/cva/debugger_user5/anhong/.remote_config/configure/.vim/bundle/LeaderF-master/autoload/leaderf/python/leaderf/anyExpl.py", line 711, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/lan/cva/debugger_user5/anhong/.remote_config/configure/.vim/bundle/LeaderF-master/autoload/leaderf/python/leaderf/fileExpl.py", line 729, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/lan/cva/debugger_user5/anhong/.remote_config/configure/.vim/bundle/LeaderF-master/autoload/leaderf/python/leaderf/manager.py", line 1989, in startExplorer
    self._getInstance().enterBuffer(win_pos, not isinstance(content, list))
  File "/lan/cva/debugger_user5/anhong/.remote_config/configure/.vim/bundle/LeaderF-master/autoload/leaderf/python/leaderf/instance.py", line 956, in enterBuffer
    self._createPopupWindow(clear)
  File "/lan/cva/debugger_user5/anhong/.remote_config/configure/.vim/bundle/LeaderF-master/autoload/leaderf/python/leaderf/instance.py", line 518, in _createPopupWindow
    lfCmd("silent let winid = popup_create(%d, %s)" % (buf_number, str(options)))
vim.error: Vim(find):E345: Can't find file "/grid/common/pkgs/vim/v8.2/share/vim/vim82/File/LeaderF" in path
Error detected while processing function leaderf#Any#start:
line    4:
E171: Missing :endif
```
and following ctrl-p would never respond.

If I comment out the ``let g:Lf_WindowPosition = 'popup'`` in the .vimrc, then it works, but without popup support, then I can use :Leaderf file --popup to use the popup window.

- vim or neovim?
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 17 2020 09:21:58)
Compiled by matrix@vlsj-ctrh65
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_old_static
-arabic            +file_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +find_in_path      +mouse_xterm       +tcl/dyn
+autochdir         +float             +multi_byte        +termguicolors
-autoservername    +folding           +multi_lang        +terminal
+balloon_eval      -footer            -mzscheme          +terminfo
+balloon_eval_term +fork()            +netbeans_intg     +termresponse
+browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +packages          +textprop
+byte_offset       +iconv             +path_extra        +timers
+channel           +insert_expand     -perl              +title
+cindent           +job               +persistent_undo   +toolbar
+clientserver      +jumplist          +popupwin          +user_commands
+clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           +python/dyn        +visual
+comments          +linebreak         +python3/dyn       +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
+cscope            +localmap          +rightleft         +wildignore
+cursorbind        +lua               -ruby              +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con_gui    +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       +X11
+digraphs          +mouse             +sound             -xfontset
+dnd               +mouseshape        +spell             +xim
-ebcdic            +mouse_dec         +startuptime       +xpm
+emacs_tags        -mouse_gpm         +statusline        +xsmp_interact
+eval              -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/grid/common/pkgs/vim/v8.2/share/vim"
Compilation: gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12     -g -O2 -D_REENTRANT   -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc -std=gnu99   -L/usr/local/lib -Wl,--as-needed -o vim   -pthread -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lgdk_pixbuf-2.0 -lpangocairo-1.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0   -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf -lnsl  -lselinux   -lcanberra   -lacl -lattr  -L/grid/common/pkgs/lua/v5.3.5//lib -llua    -L/usr/lib -ltclstub8.5 -ldl -lieee -lm     
```
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): libpython2.7.so.1.0
- Output of `:echo &pythonthreedll`(only vim, not neovim): libpython3.7m.so.1.0
- Output of `:py print(sys.version)`: 
2.7.8 (default, Dec 11 2019, 05:28:42)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]

- Output of `:py3 print(sys.version)`: 
3.7.2 (default, Apr 22 2019, 02:54:03)
[GCC 4.8.3]

- Output of `:echo g:Lf_Debug_Cmd`: 
E121: Undefined variable: g:Lf_Debug_Cmd
- Output of `:echo g:Lf_FilesFromCache`: 
E121: Undefined variable: g:Lf_FilesFromCache
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
" config for leaderF
```vim
" still uses ctrlp shortkey
let g:Lf_ShortcutF = '<C-P>'
let g:Lf_FollowLinks = 1 
let g:Lf_PreviewInPopup = 1 
let g:Lf_WindowPosition = 'popup'
" let g:Lf_DefaultMode = 'NameOnly'
if !empty($P_HOME)
    " let g:Lf_WorkingDirectory = $P_HOME
    let g:Lf_RootMarkers = ['.P4Config', '.P4ignore']
    let g:Lf_WorkingDirectoryMode = 'a' 
endif
```

**Comment by Yggdroot** [comment]
You mean there is no error if you use `Leaderf file --popup`?

**Comment by Yggdroot** [comment]
I can not reproduce this issue, it may be a conflict with other configurations.
Please provide a minimum vimrc to reproduce it.

**Comment by etorth** [comment]
I found the reason, there are lines like:

```bash
" use cdpath to edit file
" edit file can now seach path list in $VIM_CDPATH
function! FindInCDPath(name)
    let path_backup = &path
    if empty(&path)
        let &path = join(split($VIM_CDPATH), ',')
    else
        let &path = &path . "," . join(split($VIM_CDPATH), ',')
    endif

    setlocal bufhidden=wipe
    execute 'silent keepalt find ' . fnameescape(a:name)
    let &path = path_backup
    set bufhidden<
endfunction

if !empty($VIM_CDPATH)
    autocmd BufNewFile * nested call FindInCDPath(expand('<afile>'))
endif
```

I use this to edit some files in the environmental variable VIM_CDPATH, if under current directory there isn't the named one.
But seems this gives the errors.
