### ISSUE TITLE
Error on startup with gtags enabled

### ISSUE THREAD

**Issue by webdavis** [Yggdroot/LeaderF#516]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`:
```
NVIM v0.5.0-397-g96059d72e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-13ebc8c2-4f6f-45b7-ad53-0dc3d8813d5f

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"
```
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1
- Output of `:py print(sys.version)`: `2.7.17 (default, Oct 22 2019, 09:14:09) [GCC 9.2.0]`
- Output of `:py3 print(sys.version)`: `3.8.1 (default, Jan 22 2020, 06:38:00) [GCC 9.2.0]`
- Operating system: 
    - [x] Linux (Arch Linux)
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc:
```vim
let g:Lf_AutoResize = 1
let g:Lf_GtagsAutoGenerate = 1
let g:Lf_Gtagslabel = 'native-pygments'
let g:Lf_PreviewInPopup = 1
let g:Lf_WindowPosition = 'popup'
let g:Lf_WindowHeight = 0.30
let g:Lf_PopupWidth = 0.80
let g:Lf_RootMarkers = ['.project', '.projections.json', '.git', '.hg', '.svn',]
let g:Lf_JumpToExistingWindow = 1
let g:Lf_PopupShowStatusline = 0
```
### Describe your question, feature request, or bug.
Bug, getting the following error output when starting Neovim:
```
|| Request from non-main thread.
|| Requests from different threads should be wrapped with nvim.async_call(cb, ...) 
||   File "/home/stephen/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/gtagsExpl.py", line 468, in _update
||     root, dbpath, exists = self._root_dbpath(filename)
||   File "/home/stephen/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/gtagsExpl.py", line 422, in _root_dbpath
||     dbpath = self._generateDbpath(root)
||   File "/home/stephen/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/gtagsExpl.py", line 398, in _generateDbpath
||     if lfEval("get(g:, 'Lf_GtagsStoreInProject', 0)") == '1':
||   File "/home/stephen/.local/lib/python3.8/site-packages/pynvim/plugin/script_host.py", line 207, in eval
||     obj = self.request("vim_eval", expr)
|| Request from non-main thread.
|| Requests from different threads should be wrapped with nvim.async_call(cb, ...) 
||   File "/home/stephen/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/gtagsExpl.py", line 62, in _processTask
||     print(e)
||   File "/home/stephen/.local/lib/python3.8/site-packages/pynvim/plugin/script_host.py", line 186, in write
||     self.redirect_handler(data)
||   File "/home/stephen/.local/lib/python3.8/site-packages/pynvim/plugin/script_host.py", line 77, in <lambda>
||     sys.stdout = RedirectStream(lambda data: nvim.out_write(data))
||   File "/home/stephen/.local/lib/python3.8/site-packages/pynvim/api/nvim.py", line 396, in out_write
||     return self.request('nvim_out_write', msg, **kwargs)
|| Exception in thread Thread-1:
|| Traceback (most recent call last):
||   File "/home/stephen/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/gtagsExpl.py", line 60, in _processTask
||     task()
||   File "/home/stephen/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/gtagsExpl.py", line 468, in _update
||     root, dbpath, exists = self._root_dbpath(filename)
||   File "/home/stephen/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/gtagsExpl.py", line 422, in _root_dbpath
||     dbpath = self._generateDbpath(root)
||   File "/home/stephen/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/gtagsExpl.py", line 398, in _generateDbpath
||     if lfEval("get(g:, 'Lf_GtagsStoreInProject', 0)") == '1':
||   File "/home/stephen/.local/lib/python3.8/site-packages/pynvim/plugin/script_host.py", line 207, in eval
||     obj = self.request("vim_eval", expr)
||   File "/home/stephen/.local/lib/python3.8/site-packages/pynvim/api/nvim.py", line 178, in request
||     raise NvimError("request from non-main thread")
|| pynvim.api.common.NvimError: request from non-main thread
|| During handling of the above exception, another exception occurred:
|| Traceback (most recent call last):
||   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
||     self.run()
||   File "/usr/lib/python3.8/threading.py", line 870, in run
||     self._target(*self._args, **self._kwargs)
||   File "/home/stephen/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/gtagsExpl.py", line 62, in _processTask
||     print(e)
||   File "/home/stephen/.local/lib/python3.8/site-packages/pynvim/plugin/script_host.py", line 186, in write
||     self.redirect_handler(data)
||   File "/home/stephen/.local/lib/python3.8/site-packages/pynvim/plugin/script_host.py", line 77, in <lambda>
||     sys.stdout = RedirectStream(lambda data: nvim.out_write(data))
||   File "/home/stephen/.local/lib/python3.8/site-packages/pynvim/api/nvim.py", line 396, in out_write
||     return self.request('nvim_out_write', msg, **kwargs)
||   File "/home/stephen/.local/lib/python3.8/site-packages/pynvim/api/nvim.py", line 178, in request
||     raise NvimError("request from non-main thread")
|| pynvim.api.common.NvimError: request from non-main thread
```
### Steps to reproduce
Put the following in your `vimrc`:
```vim
let g:Lf_GtagsAutoGenerate = 1
```

**Comment by webdavis** [comment]
As suggested in #315 running `Leaderf gtags --update` doesn't seem to fix this.

**Comment by cbows** [comment]
I am getting the same error on latest MacOS with NVIM v0.5.0-nightly-847-g9fb278dde and Python 3.7.6.
Even without `let g:Lf_GtagsAutoGenerate = 0`.

**Comment by jiahaowu** [comment]
Have the same error output without customizing any Leaderf configuration.

**Comment by Yggdroot** [comment]
This issue is due to my new commit, fixed.

**Comment by webdavis** [comment]
Seems to be fixed for me now.
