### ISSUE TITLE
API call: Option 'foldcolumn' requires a string value

### ISSUE THREAD

**Issue by yongqi-zhang** [Yggdroot/LeaderF#517]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`:
NVIM v0.5.0-2b00d1d09 
- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
3.7.6 (default, Jan  6 2020, 16:25:36)
- Output of `:echo g:Lf_Debug_Cmd`: 
rg --no-messages --files --color never
- Output of `:echo g:Lf_FilesFromCache`: 
0
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
let g:Lf_PreviewInPopup = 1
### Describe your question, feature request, or bug.
在开启悬浮窗口设定时，使用 leaderf 报错
ps: 已经使用过一段时间，无问题，最近一次更新后，出现此问题。
### Steps to reproduce
use leaderf file --popular
### Actual behaviour
无法使用，报错信息如下：
```
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy[1]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 5 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/zhangyongqi/.cache/vim/dein/.cache/init.vim/.dein/autoload/leaderf/python/leaderf/anyExpl.py", line 797, in start
    the_args.start(arguments, *args, **kwargs)
  File "/Users/zhangyongqi/.cache/vim/dein/.cache/init.vim/.dein/autoload/leaderf/python/leaderf/anyExpl.py", line 729, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/Users/zhangyongqi/.cache/vim/dein/.cache/init.vim/.dein/autoload/leaderf/python/leaderf/fileExpl.py", line 729, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/Users/zhangyongqi/.cache/vim/dein/.cache/init.vim/.dein/autoload/leaderf/python/leaderf/manager.py", line 1994, in startExplorer
    self._getInstance().enterBuffer(win_pos, not isinstance(content, list))
  File "/Users/zhangyongqi/.cache/vim/dein/.cache/init.vim/.dein/autoload/leaderf/python/leaderf/instance.py", line 956, in enterBuffer
    self._createPopupWindow(clear)
  File "/Users/zhangyongqi/.cache/vim/dein/.cache/init.vim/.dein/autoload/leaderf/python/leaderf/instance.py", line 406, in _createPopupWindow
    lfCmd("call nvim_win_set_option(%d, 'foldcolumn', 1)" % self._popup_winid)
  File "/usr/local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim(call):E5555: API call: Option 'foldcolumn' requires a string value
```
### Expected behaviour
可以正常使用

**Comment by Yggdroot** [comment]
奇怪，复现不了， 也许是nvim的bug，我用nvim0.4.3没问题，你的是0.5.

Option 'foldcolumn' requires a string value 有问题，就不应该是个string。

**Comment by Yggdroot** [comment]
你在你的nvim上执行一下`call nvim_win_set_option(1000, 'foldcolumn', 1)` 看看会不会报错。

**Comment by yongqi-zhang** [comment]
@Yggdroot 执行结果 ：
`E5555: API call: Option 'foldcolumn' requires a string value`
我也觉着奇怪。。

**Comment by Yggdroot** [comment]
那可以向nvim提bug了。

**Comment by yongqi-zhang** [comment]
我看到了，，
2020/03/03
#11716 foldcolumn changed from a number to a string to allow auto:X values. Also the limit was changed from 12 to 9.
地址：
https://github.com/neovim/neovim/wiki/Following-HEAD
看来我只能先切回4.x版本了

**Comment by Yggdroot** [comment]
不用切，我改一下代码吧。

**Comment by Yggdroot** [comment]
你切到dev branch试一下，没问题我merge到master上。

**Comment by yongqi-zhang** [comment]
@Yggdroot 已验证，不报错了，可以正常使用

**Comment by Yggdroot** [comment]
OK，merge了。
