### ISSUE TITLE
Too many arguments for function: getcwd

### ISSUE THREAD

**Issue by zedtang** [Yggdroot/LeaderF#519]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug  9 2019 03:17:15)
Included patches: 1-207, 209-629
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim74"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -g -pipe -Wall -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D__linux__ -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,--enable-new-dtags -Wl,-rpath,/usr/lib64/perl5/CORE  -Wl,-z,relro  -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lnsl  -lselinux  -lncurses -lacl -lattr -lgpm -ldl   -Wl,--enable-new-dtags -Wl,-rpath,/usr/lib64/perl5/CORE  -fstack-protector  -L/usr/lib64/perl5/CORE -lperl -lresolv -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
```
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 0
- Output of `:echo &pythondll`(only vim, not neovim): 
```
E113: Unknown option: pythondll
E15: Invalid expression: &pythondll
```
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
```
E113: Unknown option: pythonthreedll
E15: Invalid expression: &pythonthreedll
```
- Output of `:py print(sys.version)`: 
```
2.7.5 (default, Aug  7 2019, 00:51:29)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```
- Output of `:py3 print(sys.version)`:  nothing
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
let g:Lf_WindowHeight = 0.30
nnoremap <silent> <leader>m :LeaderfFunction!<CR>
```
### Describe your question, feature request, or bug.
When I invoke `:LeaderFunction!`, it shows the window with function list. But when I choose a function to jump to, it prompts this error message(irrelevant part are removed):
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1705, in accept
    win_local_cwd = lfEval("getcwd(winnr())")
vim.error: Vim:E118: Too many arguments for function: getcwd
Press ENTER or type command to continue
```
After press enter, it goes away and I can jump to the function.

**Comment by Yggdroot** [comment]
This version of vim is too old, please update it to 7.4.1126+.

**Comment by ZSaberLv0** [comment]
```
vim7.3 or higher. Only support vim7.4.330 or higher after v1.01.
```

maybe you should update the requirement in README?

**Comment by Yggdroot** [comment]
> ```
> vim7.3 or higher. Only support vim7.4.330 or higher after v1.01.
> ```
> 
> maybe you should update the requirement in README?

Updated.
