### ISSUE TITLE
Leaderf file error

### ISSUE THREAD

**Issue by YinZhongkai** [Yggdroot/LeaderF#581]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 8.0
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): nothing
- Output of `:echo &pythonthreedll`(only vim, not neovim): nothing
- Output of `:py print(sys.version)`: E319: Sorry, the command is not available in this version
- Output of `:py3 print(sys.version)`: 3.6.8 (default, Oct  7 2019, 12:59:55)/[GCC 8.3.0]
- Output of `:echo g:Lf_Debug_Cmd`: 
E121: Undefined variable: g:Lf_Debug_Cmd
E15: Invalid expression: g:Lf_Debug_Cmd
- Output of `:echo g:Lf_FilesFromCache`: 
E121: Undefined variable: g:Lf_FilesFromCache
E15: Invalid expression: g:Lf_FilesFromCache
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Bundle 'Valloric/YouCompleteMe'
Plugin 'Yggdroot/LeaderF', {'do': './install.sh'}
call vundle#end()

### Describe your question, feature request, or bug.

我直接打开vim，在命令行模式输入Leaderf file命令，就报下面的错误
```
 LeaderF  -  -  -                                                                                                                                                                                   0/0  Total: 0 
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yinzhongkai/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 797, in start
    the_args.start(arguments, *args, **kwargs)
  File "/home/yinzhongkai/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 729, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/home/yinzhongkai/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 808, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/home/yinzhongkai/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2028, in startExplorer
    self._getInstance().enterBuffer(win_pos, not isinstance(content, list))
  File "/home/yinzhongkai/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/instance.py", line 997, in enterBuffer
    self._after_enter()
  File "/home/yinzhongkai/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 737, in _afterEnter
    self._match_ids.extend(matchaddDevIconsExtension(icon_pattern, winid))
  File "/home/yinzhongkai/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/devicons.py", line 245, in matchaddDevIconsExtension
    return _matchadd(fileNodesExtensionSymbols, pattern, 7, winid)
  File "/home/yinzhongkai/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/devicons.py", line 205, in _matchadd
    id = int(lfEval("matchadd('{:s}', '{:s}')".format(group_name, tmp_pattern)))
UnicodeEncodeError: 'latin-1' codec can't encode character '\ue624' in position 33: ordinal not in range(256)
Error detected while processing function leaderf#Any#start:
line    4:
E171: Missing :endif
```
### Steps to reproduce

1. PluginInstall 安装 Leader
2. shell执行vim命令，打开vim
3. 在命令行模式输入Leaderf file命令，会报错

**Comment by Yggdroot** [comment]
Please `set encoding=utf-8` in vimrc.

**Comment by YinZhongkai** [comment]
在vimrc中增加这个配置项后，就可以使用了，谢谢
