### ISSUE TITLE
:LeaderfHistorySearch error

### ISSUE THREAD

**Issue by blurm** [Yggdroot/LeaderF#61]
nvim 0.2.0

error message
```
/home/damon/.vim/plugged/LeaderF/autoload/leaderf.vim|35| leaderf#LfPy[1]
|| provider#python3#Call[18]
|| Traceback (most recent call last):
||   File "<string>", line 1, in <module>
||   File "/home/damon/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 647, in startExplorer
||     content = self._getExplorer().getContent(*args, **kwargs)
||   File "/home/damon/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/historyExpl.py", line 37, in getContent
||     result_list = [line[1:].split(None, 1)[1] for line in result_list]
||   File "/home/damon/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/historyExpl.py", line 37, in <listcomp>
||     result_list = [line[1:].split(None, 1)[1] for line in result_list]
|| IndexError: list index out of range
```

**Comment by Yggdroot** [comment]
Fixed. Have a try please.
