### ISSUE TITLE
File search crashes

### ISSUE THREAD

**Issue by jm33-m0** [Yggdroot/LeaderF#616]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 12 2020 00:47:07)
macOS version
Included patches: 1-539
Compiled by travis@Traviss-Mac.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
+balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +fullscreen        +num64             +textobjects
+browse            -gettext           +odbeditor         +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     +perl/dyn          +toolbar
+cindent           +job               +persistent_undo   +transparency
+clientserver      +jumplist          +popupwin          +user_commands
+clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           +python/dyn        +visual
+comments          +linebreak         +python3/dyn       +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
+cscope            +localmap          +rightleft         +wildignore
+cursorbind        +lua/dyn           +ruby/dyn          +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con_gui    +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       -X11
+digraphs          +mouse             -sound             -xfontset
+dnd               +mouseshape        +spell             +xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE 
```

- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

```
"""""""" LeaderF
let g:Lf_ShortcutF = '<c-p>'
let g:Lf_ShortcutB = '<c-n>'
noremap <leader>u :LeaderfMru<cr>
noremap <leader>f :LeaderfFunction<cr>
noremap <leader>b :LeaderfBuffer<cr>
noremap <leader>m :LeaderfTag<cr>
noremap <leader>r :Leaderf rg<cr>
let g:Lf_StlSeparator = { 'left': '', 'right': '', 'font': '' }
" let g:Lf_WindowPosition = 'popup'

let g:Lf_RootMarkers = ['.project', '.root', '.svn', '.git']
let g:Lf_WorkingDirectoryMode = 'Ac'
let g:Lf_WindowHeight = 0.30
let g:Lf_CacheDirectory = expand('~/.vim/cache')
let g:Lf_ShowRelativePath = 0
let g:Lf_HideHelp = 1
let g:Lf_StlColorscheme = 'powerline'
let g:Lf_PreviewResult = {'Function':0, 'BufTag':0}
```

### Describe your question, feature request, or bug.

There seems to be a bug in recent updates, when trying to open File Search using <kbd>Ctrl</kbd>+<kbd>P</kbd>, I get a traceback.

### Steps to reproduce

1. `vim somefile` (when not opening any file it works fine)
2. Open leaderF's file search window

### Actual behaviour

The following traceback is thrown

```
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jm33/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 797, in start
    the_args.start(arguments, *args, **kwargs)
  File "/Users/jm33/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 729, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/Users/jm33/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 808, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/Users/jm33/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2135, in startExplorer
    self.input()
  File "/Users/jm33/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 62, in deco
    func(self, *args, **kwargs)
  File "/Users/jm33/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2343, in input
    self._guessSearch(self._content)
  File "/Users/jm33/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1388, in _guessSearch
    _, self._result_content = self._filter(step, filter_method, content, is_continue, True)
  File "/Users/jm33/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1017, in _filter
    result = filter_method(source=cur_content)
TypeError: guessMatch() takes at most 6 keyword arguments (7 given)
```

### Expected behaviour

File search listing all the related files

**Comment by Yggdroot** [comment]
Please compile the C extension, go to the root dirctory of LeaderF, run `./install.sh` or `.\install.bat`.

**Comment by jm33-m0** [comment]
I have compiled the C extension using `install.sh` again, it says both python2 and python3 extensions are built successfully.

But the problem persists, with the same traceback.

How do I check if the C extensions are working? They used to work fine until the last update

**Comment by Yggdroot** [comment]
I think it is still using the old C extension, try again:

```bash
./install.sh --reverse
./install.sh
```

**Comment by jm33-m0** [comment]
Thank you, reinstalling worked
