### ISSUE TITLE
popup模式报错

### ISSUE THREAD

**Issue by cage1618** [Yggdroot/LeaderF#632]
- vim or neovim? 
    - [x] neovim
    - [ ] vim
- Output of `vim --version` or `nvim --version`: 
`````
❯ nvim --version                                                                                                                                                                                       [17:45:01]
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
Compiled by brew@Catalina.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info
`````

`````markdown
:checkhealth

health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle build/index.js found
  - OK: Service started

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python version: 2.7.16
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Python version: 3.7.7
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v12.10.0
  - INFO: Neovim node.js host: /usr/local/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.9.0
`````

- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1
- Output of `:py print(sys.version)`: 
`````
2.7.16 (default, Apr 17 2020, 18:29:03)
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-
`````

- Output of `:py3 print(sys.version)`: 
`````
3.7.7 (default, Jun  5 2020, 00:47:03)
[Clang 11.0.3 (clang-1103.0.32.62)]
`````

- Output of `:echo g:Lf_Debug_Cmd`: 
`````
E121: Undefined variable: g:Lf_Debug_Cmd
`````

- Output of `:echo g:Lf_FilesFromCache`: 
`````
E121: Undefined variable: g:Lf_FilesFromCache
`````

- Operating system: 
    - [ ] Linux
    - [x] Mac OS X（10.15.5）
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
`````
let g:Lf_WindowHeight=15
let g:Lf_StlColorscheme="powerline"
let g:Lf_PreviewResult = { 'rg': 1 }
let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1
nmap go :Leaderf! rg --recall<CR>
nmap <leader>lf :Leaderf! --recall<CR>
`````

### Describe your question, feature request, or bug.
开启了 popup 模式后，file、buffer、rg 都报错了:
`````python
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy[1]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/cage/.vim/plugins/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 805, in start
    the_args.start(arguments, *args, **kwargs)
  File "/Users/cage/.vim/plugins/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 737, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/Users/cage/.vim/plugins/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 808, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/Users/cage/.vim/plugins/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2030, in startExplorer
    self._getInstance().enterBuffer(win_pos, not isinstance(content, list))
  File "/Users/cage/.vim/plugins/LeaderF/autoload/leaderf/python/leaderf/instance.py", line 974, in enterBuffer
    self._createPopupWindow(clear)
  File "/Users/cage/.vim/plugins/LeaderF/autoload/leaderf/python/leaderf/instance.py", line 410, in _createPopupWindow
    lfCmd("silent let winid = nvim_open_win(%d, 1, %s)" % (buf_number, str(config)))
  File "/usr/local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim(let):E5555: API call: Vim:E303: Unable to open swap file for "/usr/local/Cellar/neovim/0.4.3/share/nvim/runtime/File/LeaderF", recovery impossible
Press ENTER or type command to continue
`````

**Comment by Yggdroot** [comment]
这个错我复现不了。

**Comment by cage1618** [comment]
> 这个错我复现不了。
😭

**Comment by Yggdroot** [comment]
对你来说必现吗？如果必现请提供一个minivimrc。

**Comment by cage1618** [comment]
嗯，是必现的，试了下，设置了交换文件的目录就会出这个错误
`````
set directory=.
`````

**Comment by Yggdroot** [comment]
不设这个值保持默认就没有问题。

**Comment by cage1618** [comment]
> 不设这个值保持默认就没有问题。

是的，之前没想到会受其他配置影响

**Comment by Yggdroot** [comment]
修复了，现在即使设了`set directory=.`也不会报错了。
