### ISSUE TITLE
Exception: global: directory '***' not found. Error detected while processing function leaderf#Any#start

### ISSUE THREAD

**Issue by ltang666** [Yggdroot/LeaderF#654]
global version ： 6.6.2
os： Linux 64 bit

set `let g:Lf_GtagsAutoGenerate = 1`

![image](https://user-images.githubusercontent.com/3445470/86526171-eb5e9a80-bec2-11ea-9ffd-1eb1d89731af.png)

**Comment by tanglianggithub** [comment]
run `Leaderf gtags --update` has `gtags error!`

**Comment by Yggdroot** [comment]
What are the exact steps to reproduce?

**Comment by JasonYanHw** [comment]
我也是，跑LeaderfFile时出错：

Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yanaijie/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 805, in start
    the_args.start(arguments, *args, **kwargs)
  File "/home/yanaijie/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 737, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/home/yanaijie/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 808, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/home/yanaijie/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2139, in startExplorer
    self.input()
  File "/home/yanaijie/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 62, in deco
    func(self, *args, **kwargs)
  File "/home/yanaijie/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2354, in input
    self._guessSearch(self._content)
  File "/home/yanaijie/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1392, in _guessSearch
    _, self._result_content = self._filter(step, filter_method, content, is_continue, True)
  File "/home/yanaijie/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1021, in _filter
    result = filter_method(source=cur_content)
TypeError: guessMatch() takes at most 6 keyword arguments (7 given)
Press ENTER or type command to continue

**Comment by Yggdroot** [comment]
> 
> 
> 我也是，跑LeaderfFile时出错：

你的错误不是同一个，是https://github.com/Yggdroot/LeaderF/issues/616 。

**Comment by JasonYanHw** [comment]
> > 我也是，跑LeaderfFile时出错：
> 
> 你的错误不是同一个，是#616 。

确实，现在好了，多谢。

**Comment by tanglianggithub** [comment]
> What are the exact steps to reproduce?

`noremap <leader>fd :<C-U><C-R>=printf("Leaderf! gtags -d %s --auto-jump", expand("<cword>"))<CR><CR>
`
find definition

**Comment by Yggdroot** [comment]
> 
> 
> > What are the exact steps to reproduce?
> 
> `noremap <leader>fd :<C-U><C-R>=printf("Leaderf! gtags -d %s --auto-jump", expand("<cword>"))<CR><CR> `
> find definition

I don't know how to reproduce it.

**Comment by Yggdroot** [comment]
1. what is the configuration about LeaderF?
2. Does BufRead autocmd works well in your vim?
