### ISSUE TITLE
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:

### ISSUE THREAD

**Issue by zhanghongtong** [Yggdroot/LeaderF#662]
- LeaderF version:

    ```
    commit 4037d5d010dfdbb8cff1f6c7adf3645c6fe4b38a (HEAD -> master, origin/master, origin/dev, origin/HEAD)
    Author: Yggdroot <archofortune@gmail.com>
    Date:   Wed Jul 15 15:22:03 2020 +0800
    
        call _argaddFiles() only for File
    ```

- vim or neovim? 
    
    - [x] vim
    - [ ] neovim
    
- Output of `vim --version` or `nvim --version`: 
  
   ```
   VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 18 2020 18:29:15)
   Included patches: 1-1453
  Modified by pkg-vim-maintainers@lists.alioth.debian.org
  Compiled by pkg-vim-maintainers@lists.alioth.debian.org
  Huge version without GUI.  Features included (+) or not (-):
  +acl               +farsi             +mouse_sgr         -tag_any_white
  +arabic            +file_in_path      -mouse_sysmouse    -tcl
  +autocmd           +find_in_path      +mouse_urxvt       +termguicolors
  -autoservername    +float             +mouse_xterm       +terminal
  -balloon_eval      +folding           +multi_byte        +terminfo
  +balloon_eval_term -footer            +multi_lang        +termresponse
  -browse            +fork()            -mzscheme          +textobjects
  ++builtin_terms    +gettext           +netbeans_intg     +timers
  +byte_offset       -hangul_input      +num64             +title
  +channel           +iconv             +packages          -toolbar
  +cindent           +insert_expand     +path_extra        +user_commands
  -clientserver      +job               -perl              +vertsplit
  -clipboard         +jumplist          +persistent_undo   +virtualedit
  +cmdline_compl     +keymap            +postscript        +visual
  +cmdline_hist      +lambda            +printer           +visualextra
  +cmdline_info      +langmap           +profile           +viminfo
  +comments          +libcall           -python            +vreplace
  +conceal           +linebreak         +python3           +wildignore
  +cryptv            +lispindent        +quickfix          +wildmenu
  +cscope            +listcmds          +reltime           +windows
  +cursorbind        +localmap          +rightleft         +writebackup
  +cursorshape       -lua               -ruby              -X11
  +dialog_con        +menu              +scrollbind        -xfontset
  +diff              +mksession         +signs             -xim
  +digraphs          +modify_fname      +smartindent       -xpm
  -dnd               +mouse             +startuptime       -xsmp
  -ebcdic            -mouseshape        +statusline        -xterm_clipboard
  +emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
  +eval              +mouse_gpm         +syntax
  +ex_extra          -mouse_jsbterm     +tag_binary
  +extra_search      +mouse_netterm     +tag_old_static
     system vimrc file: "$VIM/vimrc"
       user vimrc file: "$HOME/.vimrc"
   2nd user vimrc file: "~/.vim/vimrc"
        user exrc file: "$HOME/.exrc"
         defaults file: "$VIMRUNTIME/defaults.vim"
    fall-back for $VIM: "/usr/share/vim"
  Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-dfCUyu/vim-8.0.1453=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
  Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm
  ```
  
- Output of `:echo has("python")`: 0

- Output of `:echo has("python3")`: 1

- Output of `:echo &pythondll`(only vim, not neovim):  nothing

- Output of `:echo &pythonthreedll`(only vim, not neovim): nothing

- Output of `:py print(sys.version)`: `E319: Sorry, the command is not available in this version`

- Output of `:py3 print(sys.version)`: 

    ```
    3.6.9 (default, Apr 18 2020, 01:56:04)
    [GCC 8.4.0]
    ```

- Output of `:echo g:Lf_Debug_Cmd`: 

- Output of `:echo g:Lf_FilesFromCache`: 

- Operating system: 
    - [x] Linux Ubuntu 18.04.4 LTS
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
    
- Configurations related to LeaderF in vimrc: 

    ```
    let g:Lf_WildIgnore = {
                \ 'dir': [],
                \ 'file': ['*.beam']
                \}
    let g:Lf_DefaultExternalTool = ""
    let g:Lf_UseVersionControlTool = 0
    ```

### Describe your question, feature request, or bug.

+ Useing `<leader>f`, then:

  ```
  Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
  line    1:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/home/ubuntu/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 805, in st
  art
      the_args.start(arguments, *args, **kwargs)
    File "/home/ubuntu/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 737, in _d
  efault_action
      manager.startExplorer(win_pos[2:], *args, **kwargs)
    File "/home/ubuntu/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 808, in s
  tartExplorer
      super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
    File "/home/ubuntu/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2037, in s
  tartExplorer
      self._getInstance().enterBuffer(win_pos, not isinstance(content, list))
    File "/home/ubuntu/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/instance.py", line 999, in e
  nterBuffer
      self._after_enter()
    File "/home/ubuntu/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 737, in _
  afterEnter
      self._match_ids.extend(matchaddDevIconsExtension(icon_pattern, winid))
    File "/home/ubuntu/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/devicons.py", line 509, in m
  atchaddDevIconsExtension
      return _matchadd(fileNodesExtensionSymbols, pattern, 7, winid)
    File "/home/ubuntu/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/devicons.py", line 469, in _
  matchadd
      id = int(lfEval("matchadd('{:s}', '{:s}')".format(group_name, tmp_pattern)))
  UnicodeEncodeError: 'latin-1' codec can't encode character '\ue624' in position 33: ordinal not in ra
  nge(256)
  Error detected while processing function leaderf#Any#start:
  line    4:
  E171: Missing :endif
  ```

+ Useing `:LeaderfFile`, then:

  ```
  Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
  line    1:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/home/ubuntu/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 805, in st
  art
      the_args.start(arguments, *args, **kwargs)
    File "/home/ubuntu/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 737, in _d
  efault_action
      manager.startExplorer(win_pos[2:], *args, **kwargs)
    File "/home/ubuntu/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 808, in s
  tartExplorer
      super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
    File "/home/ubuntu/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2037, in s
  tartExplorer
      self._getInstance().enterBuffer(win_pos, not isinstance(content, list))
    File "/home/ubuntu/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/instance.py", line 999, in e
  nterBuffer
      self._after_enter()
    File "/home/ubuntu/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 737, in _
  afterEnter
      self._match_ids.extend(matchaddDevIconsExtension(icon_pattern, winid))
    File "/home/ubuntu/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/devicons.py", line 509, in m
  atchaddDevIconsExtension
      return _matchadd(fileNodesExtensionSymbols, pattern, 7, winid)
    File "/home/ubuntu/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/devicons.py", line 469, in _
  matchadd
      id = int(lfEval("matchadd('{:s}', '{:s}')".format(group_name, tmp_pattern)))
  UnicodeEncodeError: 'latin-1' codec can't encode character '\ue624' in position 33: ordinal not in ra
  nge(256)
  ```

### Expected behaviour

Expecting vim to open buffer 1

**Comment by zhanghongtong** [comment]
It looks very similar to https://github.com/Yggdroot/LeaderF/issues/641 , but I happened to be on Linux

**Comment by Yggdroot** [comment]
`set encoding=utf-8`

**Comment by zhanghongtong** [comment]
Great, it worked, thanks a lot
