### ISSUE TITLE
LeaderfBuffer fails to open in new tab even with Lf_JumpToExistingWindow = 0 on older vim

### ISSUE THREAD

**Issue by serpent7776** [Yggdroot/LeaderF#665]
- vim or neovim? 
    - [X] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 18 2020 18:29:15)
Included patches: 1-1453

- Operating system: 
    - [X] Linux Ubuntu 18.04.4 LTS
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
`Lf_JumpToExistingWindow = 0`

### Describe your question, feature request, or bug.
Related to https://github.com/Yggdroot/LeaderF/issues/612, opening buffer that was already opened earlier with `:LeaderfBuffer` fails when opening in new tab with `<C-T>`. This happens **even with `let Lf_JumpToExistingWindow = 0`**
error message:
```
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 805, in start
    the_args.start(arguments, *args, **kwargs)
  File "/home/user/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2079, in startExplorer
    self.input()
  File "/home/user/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 62, in deco
    func(self, *args, **kwargs)
  File "/home/user/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2423, in input
    if self.accept('t') is None:
  File "/home/user/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1754, in accept
    self._accept(file, mode, self._getInstance().buffer, line_nr) # for bufTag
  File "/home/user/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1651, in _accept
    self._acceptSelection(file, *args, **kwargs)
  File "/home/user/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/bufExpl.py", line 137, in _acceptSelection
    lfCmd("tab drop %s" % escSpecial(buf_name))
vim.error: Vim(drop):E319: Sorry, the command is not available in this version: tab drop /path/to/file
Error detected while processing function leaderf#Any#start:
line    4:
E171: Missing :endif
```
Opening in vertical or horizontal split works fine.

### Steps to reproduce
- `:let Lf_JumpToExistingWindow = 0`
- `:e file_a`
- `:e file_b`
- `:LeaderfBuffer`
- select buffer with `file_a`
- open in a tab with `<C-T>`

### Actual behaviour
- buffer doesn't open, error occurs

### Expected behaviour
- `file_b` should be opened in a new tab

**Comment by Yggdroot** [comment]
Fixed.
