### ISSUE TITLE
":Leaderf function" does not work. It throws an error

### ISSUE THREAD

**Issue by lucypero** [Yggdroot/LeaderF#669]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
```NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN


Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```
- Output of `:echo has("python")`: 
`1`
- Output of `:echo has("python3")`: 
`1`
- Output of `:py print(sys.version)`: 
```2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]```
- Output of `:py3 print(sys.version)`: 
```3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)]```
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```let g:Lf_RootMarkers = ['.git']
let g:Lf_ExternalCommand = 'rg --files --no-ignore "%s"'
let g:Lf_DefaultExternalTool = 'rg'
let g:Lf_WindowPosition = 'popup'
```

### Describe your question, feature request, or bug.
`:Leaderf function` does not work. It throws an error

### Steps to reproduce
`:Leaderf function`

### Actual behaviour
```Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
E28: No such highlight group name: Lf_hl_match_refine
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy[1]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Admin\.local\share\nvim\plugged\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 805, in start
    the_args.start(arguments, *args, **kwargs)
  File "C:\Users\Admin\.local\share\nvim\plugged\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 737, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "C:\Users\Admin\.local\share\nvim\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 2014, in startExplorer
    content = self._getExplorer().getContent(*args, **kwargs)
  File "C:\Users\Admin\.local\share\nvim\plugged\LeaderF\autoload\leaderf\python\leaderf\functionExpl.py", line 80, in getContent
    result = self._formatResult(*result)
  File "C:\Users\Admin\.local\share\nvim\plugged\LeaderF\autoload\leaderf\python\leaderf\functionExpl.py", line 147, in _formatResult
    output = [line.split('\t') for line in result]
  File "C:\Users\Admin\.local\share\nvim\plugged\LeaderF\autoload\leaderf\python\leaderf\functionExpl.py", line 147, in <listcomp>
    output = [line.split('\t') for line in result]
  File "C:\Users\Admin\.local\share\nvim\plugged\LeaderF\autoload\leaderf\python\leaderf\asyncExecutor.py", line 102, in read
    raise Exception(lfBytes2Str(err, encoding))
Exception: 'ctags' is not recognized as an internal or external command,

operable program or batch file.
```

### Expected behaviour

It should display a list of the functions in the current buffer.

**Comment by Yggdroot** [comment]
please install ctags.

**Comment by lucypero** [comment]
Oh yeah.. Didn't know that command used ctags. Thank you.
