### ISSUE TITLE
Vim:E344: Can't find directory "C:\Program Files\Python37\libs" in cdpath

### ISSUE THREAD

**Issue by ebinhua** [Yggdroot/LeaderF#677]
- vim or neovim? 
    - [x ] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ x] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
using the vim in git bash of windows
when open the file found,
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Users\ebinhua\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 805, in start
    the_args.start(arguments, *args, **kwargs)
  File "c:\Users\ebinhua\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 737, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "c:\Users\ebinhua\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\fileExpl.py", line 808, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "c:\Users\ebinhua\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 2083, in startExplorer
    self.input()
  File "c:\Users\ebinhua\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 62, in deco
    func(self, *args, **kwargs)
  File "c:\Users\ebinhua\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 2418, in input
    if self.accept() is None:
  File "c:\Users\ebinhua\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 1753, in accept
    chdir(cwd)
vim.error: Vim:E344: Can't find directory "C:\Program Files\Python37\libs" in cdpath
Error detected while processing function leaderf#Any#start:
line    4:
E171: Missing :endif

**Comment by Yggdroot** [comment]
**Steps to reproduce**

**Comment by ebinhua** [comment]
I think it is because I using the vim in Msys2, but the python is installed in Windows. and I setting this set pythonthreedll=/c/Program\ Files/Python37/lib/python3.dll. which can trigger the python in leaderf , but the python is work in windows, so the path is in windows format, and cause the problem.

**Comment by ebinhua** [comment]
I think it is because I using the vim in Msys2, but the python is installed in Windows. and I setting this set pythonthreedll=/c/Program\ Files/Python37/lib/python3.dll. which can trigger the python in leaderf , but the python is work in windows, so the path is in windows format, and cause the problem.

I installed the python in Msys2，by “pacman -S python“. and remain the default setting of pythonthreedll in vim, then the problem fixed.
