### ISSUE TITLE
vim.error: Vim:E117: Unknown function: win_id2win

### ISSUE THREAD

**Issue by walkerdu** [Yggdroot/LeaderF#715]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 7.4.629
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 0
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 2.7.5 (default, Nov 20 2015, 02:00:19)                                     [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

When I Enter `LeaderF File` mode，and input‘Ctrl+J’，then report this error message！

`
 LeaderF ► File ► FullPath ► /data/home/walkerdu/REDServer/zonesvr/scripts ►         ◄ 1/4 ◄ Total: 4 
Error detected while processing function leaderf#Any#start..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/home/walkerdu/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 813
, in start
    the_args.start(arguments, *args, **kwargs)
  File "/data/home/walkerdu/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 745
, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/data/home/walkerdu/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 80
8, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/data/home/walkerdu/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 216
4, in startExplorer
    self.input()
  File "/data/home/walkerdu/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 62,
 in deco
    func(self, *args, **kwargs)
  File "/data/home/walkerdu/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 247
3, in input
    self._previewResult(False)
  File "/data/home/walkerdu/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 375
, in _previewResult
    if int(lfEval("win_id2win(%d)" % self._preview_winid)) != vim.current.window.number:
vim.error: Vim:E117: Unknown function: win_id2win
Error detected while processing function leaderf#Any#start:
line    4:
E171: Missing :endif
`

**Comment by Yggdroot** [comment]
Fixed.
