### ISSUE TITLE
Leaderf quickfix 无效的 lnum error

### ISSUE THREAD

**Issue by roachsinai** [Yggdroot/LeaderF#725]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 17 2020 21:54:53)
包含补丁: 1-1704
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): libpython2.7.so.1.0
- Output of `:echo &pythonthreedll`(only vim, not neovim):libpython3.8.so.1.0 
- Output of `:py3 print(sys.version)`: 3.8.6 (default, Sep 30 2020, 04:00:38)
[GCC 10.2.0]
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

Leaderf quickfix got error:

```
处理 function leaderf#Any#start[4]..leaderf#LfPy[1]..function leaderf#Any#start[4]..leaderf#LfPy 时发生错误:
第    1 行:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/roach/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 813, in start
    the_args.start(arguments, *args, **kwargs)
  File "/home/roach/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 745, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/home/roach/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2178, in startExplorer
    self._getInstance().setBuffer(self._content[:self._initial_count])
  File "/home/roach/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/instance.py", line 1151, in setBuffer
    self._buffer_object[:] = content
vim.error: Vim:E315: ml_get: 无效的 lnum: 16
处理 function leaderf#Any#start 时发生错误:
第    4 行:
E171: 缺少 :endif
请按 ENTER 或其它命令继续
```

### Steps to reproduce

Use `Git difftool` to load changes to quickfix list, `Git difftool` is provided by vim-fugitive. Use `:Leaderf quickfix` to trigger float window, then use `Esc` to quit (I did this by accident in fact). Use `:Leaderf quickfix` again got error above.

**Comment by Yggdroot** [comment]
E315一般是vim的bug。

**Comment by roachsinai** [comment]
昨天试了几次都可以，今天没有办法复现。

**Comment by Yggdroot** [comment]
什么时候能稳定复现，把步骤记下来，我再看看能不能不用leaderf来复现，给Vim报个bug去。

**Comment by roachsinai** [comment]
好的。

**Comment by roachsinai** [comment]
复现步骤：

```
git clone https://github.com/open-mmlab/mmdetection.git
cd mmdetection
vim tools/train.py
:Leaderf file
```

出现float window之后依次输入`datapip`在输入最后一个字符`p`的时候会报以下错误：

```
处理 function leaderf#Any#start[4]..leaderf#LfPy[1]..function leaderf#Any#start[4]..leaderf#LfPy 时发生错误:
第    1 行:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/roach/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 815, in start
    the_args.start(arguments, *args, **kwargs)
  File "/home/roach/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 747, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/home/roach/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 808, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/home/roach/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2265, in startExplorer
    self.input()
  File "/home/roach/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 62, in deco
    func(self, *args, **kwargs)
  File "/home/roach/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2491, in input
    self._search(cur_content)
  File "/home/roach/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1059, in _search
    self._fuzzySearch(content, is_continue, step)
  File "/home/roach/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1455, in _fuzzySearch
    self._getInstance().setBuffer(self._result_content[:self._initial_count])
  File "/home/roach/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/instance.py", line 1151, in setBuffer
    self._buffer_object[:] = content
vim.error: Vim:E315: ml_get: 无效的 lnum: 18
处理 function leaderf#Any#start 时发生错误:
第    4 行:
E171: 缺少 :endif
请按 ENTER 或其它命令继续
```

发生这个错误之后，我无法输入`echo g:Lf_Debug_Cmd`得到信息，Enter什么的都是乱码了。

**Comment by Yggdroot** [comment]
很遗憾，还是复现不了。能提供一个最小的vimrc吗？

**Comment by roachsinai** [comment]
好的，我试试。

**Comment by roachsinai** [comment]
> 很遗憾，还是复现不了。能提供一个最小的vimrc吗？

Y大，是安装插件`Plug 'tmhedberg/SimpylFold'`导致的这个报错。

**Comment by Yggdroot** [comment]
装了Plug 'tmhedberg/SimpylFold'还是复现不了，最好能提供minvimrc和复现步骤。

**Comment by roachsinai** [comment]
嗯嗯，麻烦测试一下下面的vimrc和复现步骤。

## minimal_vimrc

```
" 定义快捷键的前缀，即<leader>
let mapleader=" "
let g:plug_timeout = 30
call plug#begin('~/.vim/plugged')
" {{{plugins free
Plug 'Yggdroot/LeaderF', { 'do': ':LeaderfInstallCExtension' }
set hidden
let g:Lf_RootMarkers = ['.project', '.root', '.svn', '.git', '.hg']

let g:Lf_GtagsAutoGenerate = 1
let g:Lf_Gtagslabel = 'native-pygments'
let g:Lf_GtagsSource = 2
let g:Lf_GtagsfilesCmd = {
        \ '.git': 'git ls-files --recurse-submodules',
        \ '.hg': 'hg files',
        \ 'default': 'rg --no-messages --files'
        \}

let g:Lf_DefaultExternalTool='rg'
let g:Lf_IgnoreCurrentBufferName = 1
let g:Lf_NormalMap = {
	\ "File":   [["<ESC>", ':exec g:Lf_py "fileExplManager.quit()"<CR>']],
	\ "Buffer": [["<ESC>", ':exec g:Lf_py "bufExplManager.quit()"<CR>']],
	\ "Mru":    [["<ESC>", ':exec g:Lf_py "mruExplManager.quit()"<CR>']],
	\ "Tag":    [["<ESC>", ':exec g:Lf_py "tagExplManager.quit()"<CR>']],
	\ "BufTag":    [["<ESC>", ':exec g:Lf_py "bufTagExplManager.quit()"<CR>']],
	\ "Function":    [["<ESC>", ':exec g:Lf_py "functionExplManager.quit()"<CR>']],
	\ "Colorscheme":    [["<ESC>", ':exec g:Lf_py "colorschemeExplManager.quit()"<CR>']],
	\ }

let g:Lf_MruMaxFiles = 2048
let g:Lf_StlSeparator = { 'left': "\ue0b0", 'right': "\ue0b2", 'font': ''}
let g:Lf_StlColorscheme = 'powerline'

let g:Lf_WorkingDirectoryMode = 'Ac'
let g:Lf_WindowHeight = 0.30
let g:Lf_ShowRelativePath = 1
let g:Lf_CursorBlink = 0
let g:Lf_JumpToExistingWindow = 0

let g:Lf_WildIgnore = {
            \ 'dir': ['.svn','.git','.hg'],
            \ 'file': ['*.sw?','~$*','*.bak','*.exe','*.o','*.so','*.py[co]']
			\ }

let g:Lf_MruFileExclude = ['*.so', '*.exe', '*.py[co]', '*.sw?', '~$*', '*.bak', '*.tmp', '*.dll']

if (exists('*popup_create') && has('patch-8.1.2000')) || has('nvim-0.4')
	let g:Lf_WindowPosition = 'popup'
    let g:Lf_PreviewInPopup = 1
endif

"----------------------------------------------------------------------
" keymap
"----------------------------------------------------------------------
let g:Lf_ShortcutF = '<leader>e'
" noremap <leader>el :LeaderfFile %:p:h<CR>
let g:Lf_ShortcutB = '<leader>fb'

noremap <leader>fs :LeaderfSelf<CR>
" noremap <leader>fb :<C-U><C-R>=printf("Leaderf buffer %s", "")<CR><CR>
noremap <leader>ff :<C-U><C-R>=printf("Leaderf function %s", "")<CR><CR>
noremap <leader>af :LeaderfFunctionAll<CR>
noremap <leader>am :<C-U><C-R>=printf("Leaderf mru %s", "")<CR><CR>
noremap <leader>fm :LeaderfMruCwd<CR>
noremap <leader>ft :<C-U><C-R>=printf("Leaderf bufTag %s", "")<CR><CR>
noremap <leader>at :LeaderfBufTagAll<CR>
noremap <leader>fl :<C-U><C-R>=printf("Leaderf line %s", "")<CR><CR>
noremap <leader>al :LeaderfLineAll<CR>

noremap <leader>fw :<C-U><C-R>=printf("Leaderf! rg --current-buffer -e %s ", expand("<cword>"))<CR><CR>
noremap <leader>aw :<C-U><C-R>=printf("Leaderf! rg -e %s ", expand("<cword>"))<CR><CR>
noremap <leader>fi :<C-U><C-R>=printf("Leaderf! rg --current-buffer -e %s", input(""))<CR><CR>
noremap <leader>ai :<C-U><C-R>=printf("Leaderf! rg -e %s", input(""))<CR><CR>
" search visually selected text literally
xnoremap <leader>fv :<C-U><C-R>=printf("Leaderf! rg --current-buffer -e %s ", leaderf#Rg#visual())<CR><CR>
xnoremap <leader>av :<C-U><C-R>=printf("Leaderf! rg -F -e %s ", leaderf#Rg#visual())<CR><CR>
noremap <leader>frr :<C-U>Leaderf! rg --recall<CR>

noremap <leader>fr :<C-U><C-R>=printf("Leaderf! gtags -r %s --auto-jump", expand("<cword>"))<CR><CR>
noremap <leader>fd :<C-U><C-R>=printf("Leaderf! gtags -d %s --auto-jump", expand("<cword>"))<CR><CR>
noremap <leader>fgr :<C-U><C-R>=printf("Leaderf! gtags --recall %s", "")<CR><CR>
noremap <leader>fn :<C-U><C-R>=printf("Leaderf gtags --next %s", "")<CR><CR>
noremap <leader>fp :<C-U><C-R>=printf("Leaderf gtags --previous %s", "")<CR><CR>

Plug 'tmhedberg/SimpylFold'
" }}}
call plug#end()


nmap <leader>in :PlugInstall<CR>
nmap <leader>ug :PlugUpgrade<CR>
nmap <leader>ud :PlugUpdate<CR>

" Plug 'roachsinai/vim-barbaric'
" let g:barbaric_scope = 'buffer'
" key code delay https://www.johnhawthorn.com/2012/09/vi-escape-delays/
```

## 复现步骤：

```
git clone https://github.com/open-mmlab/mmdetection.git
cd mmdetection
vim tools/train.py
:Leaderf file
```

然后输入`datapip`

**Comment by Yggdroot** [comment]
复现了。

**Comment by Yggdroot** [comment]
给vim提了个bug，https://github.com/vim/vim/issues/7598， 等着他修复吧

**Comment by roachsinai** [comment]
嗯嗯，好的。

**Comment by Yggdroot** [comment]
Bram修复了这个问题，效率真高。你用最新的Vim试一下看看。

**Comment by roachsinai** [comment]
嗯嗯。

> hundred-and-one symptoms of being an internet addict: 91. It's Saturday afternoon in the middle of May and you are on computer.

😃

**Comment by Yggdroot** [comment]
> 嗯嗯。
> 
> > hundred-and-one symptoms of being an internet addict: 91. It's Saturday afternoon in the middle of May and you are on computer.
> 

这句话什么意思？

**Comment by roachsinai** [comment]
91个你有网瘾的症状第91条：五月中旬的周六下午你还在电脑前。😃

**Comment by roachsinai** [comment]
![image](https://user-images.githubusercontent.com/9500049/103471751-cf2eae00-4dbe-11eb-97f5-28f51ae331df.png)

应该是修复了。
