### ISSUE TITLE
Too many arguments for function: getmatches

### ISSUE THREAD

**Issue by Zeeech** [Yggdroot/LeaderF#729]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 

NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.0.4
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/builddir/build/BUILD/neovim-nightly/build/config -I/builddir/build/BUILD/neovim-nightly/src -I/usr/include -I/builddir/build/BUILD/neovim-nightly/build/src/nvim/auto -I/builddir/build/BUILD/neovim-nightly/build/include
Compiled by mockbuild

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

- Output of `:echo has("python")`: 
1
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 

3.7.0 (default, Nov 20 2020, 05:13:24)
[GCC 5.3.0]

- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux(centos7)
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
let g:Lf_ShortcutF = '<C-P>
let g:Lf_PreviewInPopup = 1
let g:Lf_WindowPosition = 'popup'

popwindow error

Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy[1]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mychain/.config/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 812, in start
    the_args.start(arguments, *args, **kwargs)
  File "/home/mychain/.config/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 744, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/home/mychain/.config/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 808, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/home/mychain/.config/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2138, in startExplorer
    self._getInstance().enterBuffer(win_pos, not isinstance(content, list))
  File "/home/mychain/.config/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/instance.py", line 989, in enterBuffer
    self._createPopupWindow(clear)
  File "/home/mychain/.config/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/instance.py", line 411, in _createPopupWindow
    lfCmd("silent noswapfile let winid = nvim_open_win(%d, 1, %s)" % (buf_number, str(config)))
  File "/usr/local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim(let):E5555: API call: Vim(let):E118: Too many arguments for function: getmatches

**Comment by Yggdroot** [comment]
What is the steps to reproduce it? I can not reproduce it with `
:version
NVIM v0.5.0-f7aeac7
Build type: Release
LuaJIT 2.0.5`
