### ISSUE TITLE
exception under Windows with Cygwin without gtags

### ISSUE THREAD

**Issue by ZSaberLv0** [Yggdroot/LeaderF#733]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
    ```
    VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2019 13:30:17)
    MS-Windows 32-bit GUI version with OLE support
    ```
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): `python27.dll`
- Output of `:echo &pythonthreedll`(only vim, not neovim): `python36.dll`
- Output of `:py print(sys.version)`: `E370: Could not load library python27.dllE263: Sorry, this command is disabled, the Python library could not be loaded.`
- Output of `:py3 print(sys.version)`: `3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 12:45:02) [MSC v.1900 32 bit (Intel)]`
- Output of `:echo g:Lf_Debug_Cmd`: undefined
- Output of `:echo g:Lf_FilesFromCache`: undefined
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: nothing special

### Describe your question, feature request, or bug.
env:
Windows gVim, with Cygwin in `PATH`, but no `gtags` installed

save any file, the error occasionally occur:
```
Error detected while processing function leaderf#Gtags#updateGtags:
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Program\gVimPortable\Data\settings\.vim\bundle\LeaderF\autoload\leaderf\python\leaderf\gtagsExpl.py", line 983, in updateGtags
    self._getExplorer().updateGtags(filename, single_update, auto)
  File "D:\Program\gVimPortable\Data\settings\.vim\bundle\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 887, in _getExplorer
    self._explorer = self._getExplClass()()
  File "D:\Program\gVimPortable\Data\settings\.vim\bundle\LeaderF\autoload\leaderf\python\leaderf\gtagsExpl.py", line 41, in __init__
    self._gtags_version = self._getGtagsVersion()
  File "D:\Program\gVimPortable\Data\settings\.vim\bundle\LeaderF\autoload\leaderf\python\leaderf\gtagsExpl.py", line 902, in _getGtagsVersion
    proc = subprocess.Popen("gtags --version", shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=env)
  File "C:\Python\Lib\subprocess.py", line 667, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\Python\Lib\subprocess.py", line 905, in _get_handles
    p2cread = self._make_inheritable(p2cread)
  File "C:\Python\Lib\subprocess.py", line 955, in _make_inheritable
    _winapi.DUPLICATE_SAME_ACCESS)
OSError: [WinError 6] 句柄无效。
```

### Steps to reproduce
unknown, just save any file

**Comment by Yggdroot** [comment]
Fixed.
