### ISSUE TITLE
An error occurred under Neovim

### ISSUE THREAD

**Issue by waruqi** [Yggdroot/LeaderF#75]
When I save the current file and switch to search for other files, an error occurs. And the same configuration is normal on vim
 
```
 searching ...
处理 function leaderf#Buffer#startExpl[2]..leaderf#LfPy[1]..provider#python#Call 时发生错误:
第   18 行:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ruki/.vim/autoload/leaderf/python/leaderf/manager.py", line 725, in startExplorer
    self._getInstance().enterBuffer(win_pos)
  File "/Users/ruki/.vim/autoload/leaderf/python/leaderf/instance.py", line 191, in enterBuffer
    self._createBufWindow(win_pos)
  File "/Users/ruki/.vim/autoload/leaderf/python/leaderf/instance.py", line 107, in _createBufWindow
    del self._buffer_object[:]
  File "/usr/local/lib/python2.7/site-packages/neovim/api/buffer.py", line 84, in __delitem__
    self.__setitem__(idx, None)
  File "/usr/local/lib/python2.7/site-packages/neovim/api/buffer.py", line 65, in __setitem__
    return self.request('buffer_set_lines', start, end, False, lines)
  File "/usr/local/lib/python2.7/site-packages/neovim/api/common.py", line 44, in request
    return self._session.request(name, self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/neovim/api/nvim.py", line 131, in request
    r
```

**Comment by Yggdroot** [comment]
I think this is a bug of neovim.

**Comment by Yggdroot** [comment]
Can not reproduce it on my neovim(`NVIM v0.2.1-826-g7bfa440`).

**Comment by waruqi** [comment]
Maybe my neovim version is too old (v0.1.7) and It works fine after upgrading neovim to v0.2.0.

Thanks! 😄
