### ISSUE TITLE
window git mintty vim  leaderf Can't find directory

### ISSUE THREAD

**Issue by colinquan** [Yggdroot/LeaderF#754]
- vim or neovim? 
    - [ x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- $ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 25 2020 11:44:06)
Included patches: 1-1895
Compiled by <https://www.msys2.org/>

- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Actual behaviour
 1 ? mi/mi_demo_display.h
  2  mi/mi_demo_display.c
  3 ? mi/mi_demo_disp.h
  4 ? mi/mi_demo_dbg.h
  5 ? mi/mi_demo_dmx.h                                                                                                                                                                       
  6 ? mi/mi_demo_dsc.h
  7 ? mi/mi_demo_dtv.h
  8 ? mi/mi_demo_ir.h
  9 ? mi/mi_demo_kl.h
 10 ? mi/mi_demo_mm.h
 11 ? mi/mi_demo_os.h
 12 ? mi/mi_demo_pm.h
 13 ? mi/mi_demo_si.h
 14 ? mi/mi_demo_afe.h
 15 ? mi/mi_demo_cap.h
 16 ? mi/mi_demo_cec.h
 LeaderF  File  FullPath  C:\Users\xiaoming\git\c2p\mi\MI_project\project\demo                                                                                             7/201  Total: 201 
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy[1]..function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Users\xiaoming\.vim\plugged\LeaderF-master\autoload\leaderf\python\leaderf\anyExpl.py", line 815, in start
    the_args.start(arguments, *args, **kwargs)
  File "c:\Users\xiaoming\.vim\plugged\LeaderF-master\autoload\leaderf\python\leaderf\anyExpl.py", line 747, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "c:\Users\xiaoming\.vim\plugged\LeaderF-master\autoload\leaderf\python\leaderf\fileExpl.py", line 808, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "c:\Users\xiaoming\.vim\plugged\LeaderF-master\autoload\leaderf\python\leaderf\manager.py", line 2205, in startExplorer
    self.input()
  File "c:\Users\xiaoming\.vim\plugged\LeaderF-master\autoload\leaderf\python\leaderf\manager.py", line 62, in deco
    func(self, *args, **kwargs)
  File "c:\Users\xiaoming\.vim\plugged\LeaderF-master\autoload\leaderf\python\leaderf\manager.py", line 2539, in input
    if self.accept() is None:
  File "c:\Users\xiaoming\.vim\plugged\LeaderF-master\autoload\leaderf\python\leaderf\manager.py", line 1870, in accept
    chdir(cwd)
vim.error: Vim:E344: Can't find directory "C:\Users\xiaoming\git\c2p\mi\MI_project\project\demo" in cdpath
Error detected while processing function leaderf#Any#start:
line    4:
E171: Missing :endif
Press ENTER or type command to continue

**Comment by Yggdroot** [comment]
I don't have environment to reproduce it.
What is `cdpath` ?
Can you try the following:
```vim
:pyx  import vim,os
:pyx  os.chdir(os.getcwd())
```
