### ISSUE TITLE
在leaderF弹框快速输入 "scanner-b"时出现异常：

### ISSUE THREAD

**Issue by hello-wood** [Yggdroot/LeaderF#780]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`:  

```
     VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31)
包含补丁: 1-2269
修改者 team+vim@tracker.debian.org
编译者 team+vim@tracker.debian.org
巨型版本 无图形界面。  可使用(+)与不可使用(-)的功能:
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       +tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
-balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
-browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     +perl              -toolbar
+cindent           +job               +persistent_undo   +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          +ruby              +wildmenu
+cursorbind        +lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con        +mksession         +smartindent       -X11
+diff              +modify_fname      +sound             -xfontset
+digraphs          +mouse             +spell             -xim
-dnd               -mouseshape        +startuptime       -xpm
-ebcdic            +mouse_dec         +statusline        -xsmp
+emacs_tags        +mouse_gpm         -sun_workshop      -xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary
+extra_search      +mouse_sgr         -tag_old_static
     系统 vimrc 文件: "$VIM/vimrc"
     用户 vimrc 文件: "$HOME/.vimrc"
 第二用户 vimrc 文件: "~/.vim/vimrc"
      用户 exrc 文件: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
         $VIM 预设值: "/usr/share/vim"
编译方式: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-iU6mZD/vim-8.1.2269=. -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
链接方式: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lcanberra -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.30/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu -lpython3.8 -lcrypt -lpthread -ldl -lutil -lm -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-2.7 -lm
```
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
  
  3.8.5 (default, Jan 27 2021, 15:41:15)
  [GCC 9.3.0]

- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

在leaderF弹框快速输入 "scanner-b"时出现异常：
```
处理 function leaderf#Any#start[4]..leaderf#LfPy 时发生错误:
第    1 行:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/wood/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 815, in start
    the_args.start(arguments, *args, **kwargs)
  File "/home/wood/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 747, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/home/wood/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/rgExpl.py", line 884, in startExplorer
    super(RgExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/home/wood/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2294, in startExplorer
    self.input()
  File "/home/wood/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 62, in deco
    func(self, *args, **kwargs)
  File "/home/wood/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2520, in input
    self._search(cur_content)
  File "/home/wood/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1067, in _search
    self._fuzzySearch(content, is_continue, step)
  File "/home/wood/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1492, in _fuzzySearch
    self._highlight_method()
  File "/home/wood/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1640, in _highlight
    start_pos = self._getDigestStartPos(content[unit*i], 0 if is_full_path else 1)
  File "/home/wood/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/rgExpl.py", line 628, in _getDigestStartPos
    file_path, line_num, content = line.split(":", 2)
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by Yggdroot** [comment]
你是直接：Leaderf rg 然后快速输入"scanner-b"吗？慢速输入有问题吗？也就是跟快慢有关系吗？
能否提供个截图？因为跟你的要搜索的内容有关，我这里复现不了。

**Comment by hello-wood** [comment]
![image](https://user-images.githubusercontent.com/7608370/111606391-20710a00-8812-11eb-9fc4-0f631547b6ad.png)
貌似跟输入快慢也没关系，能复现的时候一直能复现。退出vim重进后如果正常又复现不了。
发生错误后leaderf的弹框就关不了了，只有命令行能用。

**Comment by Yggdroot** [comment]
出错关不了，按Ctrl-C可以关掉。
在  File "/home/wood/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/rgExpl.py", line 628, in _getDigestStartPos
改为
try：
    file_path, line_num, content = line.split(":", 2)
except:
    print (line) 
看看
这

**Comment by hello-wood** [comment]
xWARNING: stopped searching binary file src/security-scanner-frontend/dist/fonts/ionicons.a558ac78.eot after match (found "\u{0}" byte around offset 3)

**Comment by hello-wood** [comment]
> 出错关不了，按Ctrl-C可以关掉。
> 在 File "/home/wood/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/rgExpl.py", line 628, in _getDigestStartPos
> 改为
> try：
> file_path, line_num, content = line.split(":", 2)
> except:
> print (line)
> 看看
> 这

WARNING: stopped searching binary file src/security-scanner-frontend/dist/fonts/ionicons.a558ac78.eot after match (found "\u{0}" byte around offset 3)

**Comment by Yggdroot** [comment]
奇怪，warning怎么跑到output里去了，不应该输出到stderr里面吗？

**Comment by hello-wood** [comment]
> 奇怪，warning怎么跑到output里去了，不应该输出到stderr里面吗？

我也以为不太对，加了标志，确实打印的是这个

**Comment by Yggdroot** [comment]
试试加上这个选项：`--no-messages`

**Comment by hello-wood** [comment]
> 试试加上这个选项：`--no-messages`

加过了，还是不行。

**Comment by hello-wood** [comment]
> 在命令行上试试：`rg "" 1> /dev/null` 看看有没有输出，看看是不是确实rg把warning输出到stdout里了。

![image](https://user-images.githubusercontent.com/7608370/111762822-672b3680-88dc-11eb-9df2-bece9893da72.png)
我的环境试wsl2 ubuntu

**Comment by Yggdroot** [comment]
看来是rg的bug，只能忽略掉这类文件了。加上`-g!*.eot` 可以忽略掉以eot为后缀的文件。

**Comment by Yggdroot** [comment]
这个问题要等https://github.com/BurntSushi/ripgrep/issues/1835 修复了。
