### ISSUE TITLE
Ubuntu 16.04 在用户根目录下提示 `Exception: find: ‘./.cache’: Permission denied`

### ISSUE THREAD

**Issue by michaelHL** [Yggdroot/LeaderF#80]
在用户根目录下, 直接 `vim`, 并 `<Leader>f`, 会报如下错误:

```
Error detected while processing function leaderf#File#startExpl[2]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/useruser/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 758, in startExplorer
    self.input(content)
  File "/home/useruser/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 47, in deco
    func(self, *args, **kwargs)
  File "/home/useruser/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 805, in input
    for cmd in self._cli.input(partial(self.setContent, content)):
  File "/home/useruser/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/cli.py", line 26, in deco
    for i in func(*args, **kwargs):
  File "/home/useruser/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/cli.py", line 319, in input
    if callback() == False:
  File "/home/useruser/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 770, in setContent
    for i, line in enumerate(itertools.islice(content, 10)):
  File "/home/useruser/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/asyncExecutor.py", line 80, in read
    raise Exception(lfEncode(lfBytes2Str(err)))
Exception: find: ‘./.cache’: Permission denied
Error detected while processing function leaderf#File#startExpl:
line    2:
E171: Missing :endif
Press ENTER or type command to continue
```

但是在如下情况中不会出现问题:
1. (ubuntu 16.04)在其它目录直接leaderF不会出问题
2. (ubuntu 16.04)在根目录sudo vim，leaderF不会出问题 
3. 在CentOS 7.3下不会有任何问题

---

环境

- Ubuntu 16.04
- Vim 8.0

Vim 的编译选项为:

```
./configure --with-features=huge \
            --enable-luainterp=yes \
            --enable-rubyinterp=yes \
            --enable-perlinterp=yes \
            --enable-pythoninterp=yes \
            --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu \
            --enable-python3interp=yes \
            --with-python3-config-dir=/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu \
            --enable-fontset=yes \
            --enable-cscope=yes \
            --enable-multibyte \
            --enable-fail-if-missing \
            --enable-gui=gtk2 \
            --prefix=/usr/local
make -j4
sudo make install
```

**Comment by michaelHL** [comment]
Linux 权限的问题, 使用 `find` 命令也会报错, 解决方案:
```sh
sudo chown -R $USER ~
```
参考:
[Permission Denied running find command](https://askubuntu.com/a/863044/731390)
