### ISSUE TITLE
Exception in "/home/lw3968/.vim/pack/new/start/LeaderF/autoload/leaderf/python/leaderf/asyncExecutor.py" , line 105, in read

### ISSUE THREAD

**Issue by cowerman** [Yggdroot/LeaderF#838]
- vim or neovim? 
    - [ X] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
406 noremap <leader>fd :<C-U><C-R>=printf("Leaderf! gtags -d %s --auto-jump", expand("<cword>"))<CR><CR>

### Describe your question, feature request, or bug.
查找函数定义时，使用快捷键，出现：
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lw3968/.vim/pack/new/start/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 815, in start
    the_args.start(arguments, *args, **kwargs)
  File "/home/lw3968/.vim/pack/new/start/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 747, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/home/lw3968/.vim/pack/new/start/LeaderF/autoload/leaderf/python/leaderf/gtagsExpl.py", line 1201, in startExplorer
    super(GtagsExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/home/lw3968/.vim/pack/new/start/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2189, in startExplorer
    content = self._getExplorer().getContent(*args, **kwargs)
  File "/home/lw3968/.vim/pack/new/start/LeaderF/autoload/leaderf/python/leaderf/gtagsExpl.py", line 275, in getContent
    first_two = list(itertools.islice(content, 2))
  File "/home/lw3968/.vim/pack/new/start/LeaderF/autoload/leaderf/python/leaderf/asyncExecutor.py", line 105, in read
    raise Exception(lfBytes2Str(err, encoding))
Exception: global: directory '/home/lw3968/.LfCache/gtags/_home_lw3968_lw-dev_acrn-hypervisor' not found.

### Steps to reproduce
1. 在srouce code下面建立索引: 
find `pwd` -name *.[chS] -not -type l,d -print |gtags -i -f -
2.  vim 打开任何一个文件内的函数声明
3. 利用~/.vimrc映射的快捷键查找其定义
3. 出现上面的错误
### Actual behaviour
出现上面的错误，并未找到函数的定义
### Expected behaviour
能正确找到函数定义

**Comment by Yggdroot** [comment]
gtags不支持自己生成索引。

**Comment by cowerman** [comment]
有什么好的命令或脚本来生成索引提供给gtags么？

**Comment by cowerman** [comment]
> gtags不支持自己生成索引。

有什么好的命令或脚本来生成索引提供给gtags么？

**Comment by Yggdroot** [comment]
Leaderf gtags --update.
具体可以参考https://zhuanlan.zhihu.com/p/64842373。

**Comment by cowerman** [comment]
非常感谢，解决了我的问题。
解决方法：
let g:Lf_GtagsAutoGenerate = 1 添加到~/.vimrc
