### ISSUE TITLE
Next/Previous lead error

### ISSUE THREAD

**Issue by dllvhaobo** [Yggdroot/LeaderF#858]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
```raw
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-gOb7vg/neovim-0.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-gOb7vg/neovim-0.4.3/build/config -I/build/neovim-gOb7vg/neovim-0.4.3/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-gOb7vg/neovim-0.4.3/build/src/nvim/auto -I/build/neovim-gOb7vg/neovim-0.4.3/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 0
- Output of `:py3 print(sys.version)`: 1
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [x] WSL2-UBUNTU
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
Execute next or previous got error
noremap <leader>fo :<C-U><C-R>=printf("Leaderf! gtags --recall %s", "")<CR><CR>                    
noremap <leader>fn :<C-U><C-R>=printf("Leaderf gtags --next %s", "")<CR><CR> 
```raw
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy[1]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 5 (python3-script-host):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/lv/.config/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 815, in start
    the_args.start(arguments, *args, **kwargs)
File "/home/lv/.config/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 747, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
File "/home/lv/.config/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/gtagsExpl.py", line 1201, in startExplorer
    super(GtagsExplManager, self).startExplorer(win_pos, *args, **kwargs)
File "/home/lv/.config/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2174, in startExplorer
    if self._jumpNext() == False:
File "/home/lv/.config/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1985, in _jumpNext
    line_nr = self._getInstance().window.cursor[0]
File "/usr/lib/python3/dist-packages/pynvim/api/window.py", line 22, in cursor
    return self.request('nvim_win_get_cursor')
File "/usr/lib/python3/dist-packages/pynvim/api/common.py", line 58, in request
    return self._session.request(name, self, *args, **kwargs)
File "/usr/lib/python3/dist-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
File "/usr/lib/python3/dist-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Invalid window id
```

**Comment by Yggdroot** [comment]
I can not reproduce. Does it happen in other platform?

**Comment by dllvhaobo** [comment]
> I can not reproduce. Does it happen in other platform?

Is there any suggestion for my to track this issue?

**Comment by Yggdroot** [comment]
Your nvim is NVIM v0.4.3, please update it and have a try, I suspect it's bug of nvim.

**Comment by dllvhaobo** [comment]
> Your nvim is NVIM v0.4.3, please update it and have a try, I suspect it's bug of nvim.

I have update my neovim to 0.60. 
unfortunately，the issue could repreduced

**Comment by Yggdroot** [comment]
Fixed.

**Comment by dllvhaobo** [comment]
Thanks a lot. 
Issue do not appear after plug upgrade.
