### ISSUE TITLE
Crash when some directory has no permission to access

### ISSUE THREAD

**Issue by michaelHL** [Yggdroot/LeaderF#88]
Directories which have no permission at all like these could throw an exception:

```
% ll ~/.rstudio/viewer_history
total 88K
-rw-r--r-- 1 myuser myuser    2 Nov  2 00:19 current_index
-rw-r--r-- 1 myuser myuser  638 Nov  2 00:19 history_entries
d--------- 2 myuser myuser 4.0K Nov  2 00:19 viewhtml28ac27802dcf
d--------- 2 myuser myuser 4.0K Nov  2 00:19 viewhtml28ac2d385cdf
d--------- 2 myuser myuser 4.0K Nov  2 00:19 viewhtml28ac321a80ce
d--------- 2 myuser myuser 4.0K Nov  2 00:19 viewhtml51947ee84612
```

Of course I cannot even `cd` to those directories.

```
% cd viewhtml28ac27802dcf
cd: permission denied: viewhtml28ac27802dcf
```

And in `vim`, LeaderF complained when trying accessing those folders:

```
Error detected while processing function leaderf#File#startExpl[2]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/myuser/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 766, in startExplorer
    self.input(content)
  File "/home/myuser/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 47, in deco
    func(self, *args, **kwargs)
  File "/home/myuser/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 816, in input
    for cmd in self._cli.input(partial(self.setContent, content)):
  File "/home/myuser/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/cli.py", line 26, in deco
    for i in func(*args, **kwargs):
  File "/home/myuser/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/cli.py", line 326, in input
    if callback() == False:
  File "/home/myuser/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 778, in setContent
    for i, line in enumerate(itertools.islice(content, 10)):
  File "/home/myuser/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/asyncExecutor.py", line 80, in read
    raise Exception(lfEncode(lfBytes2Str(err)))
Exception: find: ‘./.rstudio/viewer_history/viewhtml28ac32dfc4ea’: Permission denied
find: ‘./.rstudio/viewer_history/viewhtml28acb279c7c’: Permission denied
find: ‘./.rstudio/viewer_history/viewhtml28ac526efee2’: Permission denied
find: ‘./.rstudio/viewer_history/viewhtml28ac321a80ce’: Permission denied
find: ‘./.rstudio/viewer_history/viewhtml28ac46929574’: Permission denied
find: ‘./.rstudio/viewer_history/viewhtml28ac44ef1337’: Permission denied
find: ‘./.rstudio/viewer_history/viewhtml38d72082d523’: Permission denied
find: ‘./.rstudio/viewer_history/viewhtml28ac3c57cc59’: Permission denied
find: ‘./.rstudio/viewer_history/viewhtml28ac27802dcf’: Permission denied
find: ‘./.rstudio/viewer_history/viewhtml28ac45b5d7b8’: Permission denied
find: ‘./.rstudio/viewer_history/viewhtml28ac3d62d80a’: Permission denied
find: ‘./.rstudio/viewer_history/viewhtml519449e39c31’: Permission denied
find: ‘./.rstudio/viewer_history/viewhtml28ac5570cd28’: Permission denied
find: ‘./.rstudio/viewer_history/viewhtml28ac4f454bbb’: Permission denied
find: ‘./.rstudio/viewer_history/viewhtml28ac2d385cdf’: Permission denied
find: ‘./.rstudio/viewer_history/viewhtml28ac633cf89’: Permission denied
find: ‘./.rstudio/viewer_history/viewhtml28ac74a625a1’: Permission denied
find: ‘./.rstudio/viewer_history/viewhtml28ac59c15b29’: Permission denied
find: ‘./.rstudio/viewer_history/viewhtml51947ee84612’: Permission denied
Error detected while processing function leaderf#File#startExpl:
line    2:
E171: Missing :endif
```

All settings about LeaderF is by default.

**Comment by Yggdroot** [comment]
This works as designed, I'm think of that is it necessary to suppress the error message.

**Comment by michaelHL** [comment]
@Yggdroot Maybe this trace-back would turn into error info at the bottom of vim when detecting those files in the new version. 😃
