### ISSUE TITLE
Does not work in MSYS2

### ISSUE THREAD

**Issue by feipeng8848** [Yggdroot/LeaderF#946]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
```bash
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 23 2022 04:01:15)
Included patches: 1-5117
Compiled by <https://www.msys2.org/>
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl/dyn          +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3/dyn       +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          +ruby/dyn          +wildignore
+cursorbind        -lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary
-farsi             -mouse_sysmouse    -tag_old_static
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim82"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -I/usr/include/ncursesw -march=x86-64 -mtune=generic -O2 -pipe -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -L. -pipe -fstack-protector-strong -pipe -Wl,--as-needed -o vim.exe -lm -lncursesw -lrt -liconv -lacl -lintl -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -ldl -lcrypt
```
- Output of `:echo has("python")`: 
`0`
- Output of `:echo has("python3")`: 
`1`
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
```
/mingw64/bin/libpython3.10.dll
```
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
```bash
3.16.0 (main, Aug 12 2022, 18:00:29) [GCC 12.1.0 64 bit (AMD64)]
```
- Output of `:echo g:Lf_Debug_Cmd`: 
``` bash
E21 : Undefined variable : g:Lf_Debug_Cmd
```
- Output of `:echo g:Lf_FilesFromCache`: 
 ``` bash
E21 : Undefined variable : g:Lf_FilesFromCache
```
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```bash
call plug#begin('~/.vim/plugged')
Plug 'Yggdroot/LeaderF', { 'do': ':LeaderfInstallCExtension' }
call plug#end()

let g:Lf_ShortcutF = '<C-P>'
```
### Describe your question, feature request, or bug.
vim and python is installed by command : `pacman -S vim` `pacman -S python`

in vim, enter Ctrl+p, will get this error:
```bash
Error detected while processing /home/kun/.vim/plugged/LeaderF/autoload/leaderf/Any.vim:
line   14:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'leaderf'
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'anyHub' is not defined
```

**Comment by Yggdroot** [comment]
Duplicate of #720.

**Comment by arozehnal** [comment]
I'm new here - I apologize for the silly question...
Could reinstalling the LeaderF plugin solve my problem?

I've performed a reinstallation of the plugin, including the C extension, but the result is still the same.

Based on messages like:
"Symbol PyBool_FromLong (number 1) is not exported from the dependent module vim."
I assume the problem lies in the configuration or availability of some symbols during the vim->leaderf->python communication.

I've compiled Vim to have Python3 support statically linked, but the result remains the same.  :-(

Vim reports that it has Python3 support, and the installation of LeaderF went fine...

Question:
Is there a way to verify the functionality of LeaderF outside of Vim?
Does the LeaderF plugin call any C or Python functions?
