### ISSUE TITLE
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy

### ISSUE THREAD

**Issue by JackPadan** [Yggdroot/LeaderF#968]
lastest version.

- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 13 2022 09:35:02)
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 5.15.0-53-generic  59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Output of `:py3 print(sys.version)`: Python 3.10.6
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
  syntax=cppError detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lxq/.vim/bundles/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 815, in start
    the_args.start(arguments, *args, **kwargs)
  File "/home/lxq/.vim/bundles/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 747, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/home/lxq/.vim/bundles/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2305, in startExplorer
    content = self._getExplorer().getContent(*args, **kwargs)
  File "/home/lxq/.vim/bundles/LeaderF/autoload/leaderf/python/leaderf/functionExpl.py", line 80, in getContent
    result = self._formatResult(*result)
  File "/home/lxq/.vim/bundles/LeaderF/autoload/leaderf/python/leaderf/functionExpl.py", line 147, in _formatResult
    output = [line.split('\t') for line in result]
  File "/home/lxq/.vim/bundles/LeaderF/autoload/leaderf/python/leaderf/functionExpl.py", line 147, in <listcomp>
    output = [line.split('\t') for line in result]
  File "/home/lxq/.vim/bundles/LeaderF/autoload/leaderf/python/leaderf/asyncExecutor.py", line 105, in read
    raise Exception(lfBytes2Str(err, encoding))
Exception: /bin/sh: 1: ctags: not found

### Steps to reproduce
ctrl+p in vim

### Actual behaviour
  syntax=cppError detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lxq/.vim/bundles/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 815, in start
    the_args.start(arguments, *args, **kwargs)
  File "/home/lxq/.vim/bundles/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 747, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/home/lxq/.vim/bundles/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2305, in startExplorer
    content = self._getExplorer().getContent(*args, **kwargs)
  File "/home/lxq/.vim/bundles/LeaderF/autoload/leaderf/python/leaderf/functionExpl.py", line 80, in getContent
    result = self._formatResult(*result)
  File "/home/lxq/.vim/bundles/LeaderF/autoload/leaderf/python/leaderf/functionExpl.py", line 147, in _formatResult
    output = [line.split('\t') for line in result]
  File "/home/lxq/.vim/bundles/LeaderF/autoload/leaderf/python/leaderf/functionExpl.py", line 147, in <listcomp>
    output = [line.split('\t') for line in result]
  File "/home/lxq/.vim/bundles/LeaderF/autoload/leaderf/python/leaderf/asyncExecutor.py", line 105, in read
    raise Exception(lfBytes2Str(err, encoding))
Exception: /bin/sh: 1: ctags: not found

### Expected behaviour
list all funtions

**Comment by Yggdroot** [comment]
> Exception: /bin/sh: 1: ctags: not found

Please install ctags first.
